#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n "";
firstelem=1
printf "["
/usr/ramdisk/bin/floweye app stat bridge=0 app=group sort=last showsum | \
while read appid appname flow node aup adown all per1 lup ldown lall per2 rup rdown rall nateup natedown natall theother
do
	[ "${flow}" = "0" -a "${lup}" = "0" -a "${ldown}" = "0" ] && continue;
	if [ ${firstelem} -eq 1 ]; then
		printf "{'name':'${appid}',cname:'${appname}',flowcnt:'${flow}',per:'${per2}',upbps:'${rup}','downbps':'${rdown}'}"
		firstelem=0
	else
		printf ",{'name':'${appid}',cname:'${appname}',flowcnt:'${flow}',per:'${per2}',upbps:'${rup}','downbps':'${rdown}'}"
	fi
done
echo "]"

echo -n "
";