#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n "";
FLOWEYE=/usr/ramdisk/bin/floweye
firstelem=1
printf "["
${FLOWEYE} system list | while read  flow cpu wait burst pps pktrejs theother
do
	[ "${flow}" = "flow" ] && continue
	if [ ${firstelem} -eq 1 ]; then
		printf "{ 'name': 'system','flow':'${flow}','wait':'${wait}','burst': '${burst}','pps':'${pps}','pktrej':'${pktrejs}'}"
		firstelem=0
	else
		printf ",{ 'name': 'system', 'flow':'${flow}','wait':'${wait}','burst': '${burst}','pps':'${pps}','pktrej':'${pktrejs}'}"
	fi
done
${FLOWEYE} ifmap list | while read name queue autoflow setflow pps theother
do
	[ "${name}" = "name" ] && continue
	if [ ${setflow} -ne 0 ]; then
		flow=${setflow}
	else
		flow=${autoflow}
	fi
	printf ",{ 'name': '${name}', 'flow':'${flow}','wait':'${queue}','burst': '0','pps':'${pps}','pktrej':'0'}"
done
echo "]"

echo -n "
";