#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n "";
firstelem=1
FLOWEYE=/usr/ramdisk/bin/floweye
printf "["
${FLOWEYE} nat listproxy type=routerif onlystat=1 | while read type id name ifname \
linkup disable standby dnsreqs dnsfail flowcnt inbps outbps addr theothers
do
	if [ ${firstelem} -eq 1 ]; then
		printf "{ id:'${id}',name:'${name}',ifname:'${ifname}',disabled:'${disable}',standby:'${standby}',linkup:'${linkup}',addr:'${addr}',inbps:'${inbps}',outbps:'${outbps}'}"
		firstelem=0
	else
		printf ",{ id:'${id}',name:'${name}',ifname:'${ifname}',disabled:'${disable}',standby:'${standby}',linkup:'${linkup}',addr:'${addr}',inbps:'${inbps}',outbps:'${outbps}'}"
	fi
done
echo "]"

echo -n "
";