#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n ""; 
. ../common/common.sh 
freebsdver=`uname -r | cut -d'-' -f1`

echo -n "
<script type=\"text/javascript\" src=\"/img/jq.js\"></script>
<script type=\"text/javascript\" src=\"/img/common.js\"></script>
<script language=\"javascript\">
function popupUrl(url, width, height)
{
 	ShowWindow(url, \"scrollbars=1,resizable=0\", width, height);
}
function openGroup(grpid, grpname)
{
	var url = \"/cgi-bin/Monitor/grpview?bridge=${CGI_bridge}&group=\" + grpid;
 	ShowWindow(url, \"toolbar=no,menubar=no,scrollbars=1,resizable=0,location=no\", 862, 920);
}
function showUsrgrp()
{
	var url = \"/cgi-bin/Monitor/usrgrp_view?bridge=${CGI_bridge}\";
 	ShowWindow(url, \"scrollbars=1,resizable=0,statusbar=0\", 540, 500);
}
function ipShow(ipaddr)
{
        var url = \"/cgi-bin/Monitor/ipview_data?ipaddr=\" + ipaddr;
        ShowWindow(url, \"\", 800, 750);
}
function showIPTrend()
{
        var url = \"/cgi-bin/Monitor/ip_trend\";
        ShowWindow(url, \"\", 845, 680);
}
function showTopIps(sort)
{
        var url = \"/cgi-bin/Monitor/ip_topn?browsertitle=TOP用户&statype=\" + sort; 
        ShowWindow(url, \"\", 1290, 700);
}
function showTopFlows(sort)
{
        var url = \"/cgi-bin/Monitor/flow_topn?browsertitle=TOP连接\";
        ShowWindow(url, \"\", 820, 700);
}
function showProxy(proxyname)
{
        var url;
        url = \"/cgi-bin/Monitor/proxy_show?proxyname=\" + proxyname;
        ShowWindow(url, \"\", 620, 700);
}
function showWans()
{
        var url;
        url = \"/cgi-bin/Route/proxy_list?browsertitle=WAN线路\";
        ShowWindow(url, \"\", 1220, 400);
}
function showProxys()
{
        var url;
        url = \"/cgi-bin/Route/proxy_list?browsertitle=WAN线路\";
        ShowWindow(url, \"\", 1300, 700);
}
function showApp(appid, appname)
{
        var url = \"/cgi-bin/Monitor/appview_topip?appid=\" + appid +
              \"&appname=\" + appname;
        ShowWindow(url, \"scrollbars=1,resizable=1\", 744, 760);
}
function showApps()
{
        var url = \"/cgi-bin/Monitor/app_topn?browsertitle=TOP应用\"; 
        ShowWindow(url, \"\", 1300, 700);
}
function ifShow(ifname)
{
        var url = \"/cgi-bin/Monitor/if_show?name=\" + ifname + \"&title=网络接口->\" + ifname;
        ShowWindow(url, \"\", 720, 700);
}
function appShow(name)
{
	var url = \"/cgi-bin/Monitor/appview_topip?appid=\" + name;
        ShowWindow(url, \"scrollbars=1,resizable=1\", 720, 800);
}
function infoSystem()
{
	var url = \"/cgi-bin/Monitor/info_system?browsertitle=系统信息\";
        ShowWindow(url, \"scrollbars=1,resizable=1\", 830, 750);
}
function groupStat()
{
	var url = \"/cgi-bin/Monitor/group_stat?browsertitle=系统信息\";
        ShowWindow(url, \"scrollbars=1,resizable=1\", 1200, 750);
}
function groupView(group)
{
	var url = \"/cgi-bin/Monitor/grpview?bridge=0&group=\" + group;
        ShowWindow(url, \"scrollbars=1,resizable=1\", 1120, 750);
}
function sysUpgrade()
{
	var url = \"/cgi-bin/Maintain/sys_upgrade?browsertitle=系统升级\";
        ShowWindow(url, \"scrollbars=1,resizable=1\", 820, 320);
}
function licenseUpgrade()
{
	var url = \"/cgi-bin/Maintain/license_upgrade?browsertitle=License升级\";
        ShowWindow(url, \"scrollbars=1,resizable=1\", 740, 320);
}
function dateConfig()
{
	var url = \"/cgi-bin/Maintain/date_config?browsertitle=系统时间\";
        ShowWindow(url, \"scrollbars=1,resizable=1\", 720, 200);
}
function ipQuery()
{
	var ipaddr = document.getElementById(\"ipaddr\");
	ipaddr.value = TrimAll(ipaddr.value);
	if (!IsIPAddr(ipaddr.value)) {
		alert(\"请输入IP地址!\");
		ipaddr.select();
		return;
	}
        var url = \"/cgi-bin/Monitor/ipview_data?ipaddr=\" + ipaddr.value;
        ShowWindow(url, \"\", 800, 750);
}
function getLanList()
{
        AJXS({
            type: 'POST',
            url: '/cgi-bin/Monitor/ajax_lanlist',
            error: function(status){setTimeout(getLanList, 3987);},
            success: function(data){
                var d;
                try {
                        d = eval('('+data+')');
                }catch(e) {
                        d = undefined;
                }
                if(typeof(d) == \"undefined\") {
                        setTimeout(getLanList, 1000);
                        return;
                }
                var e, i;
                var lanlist = document.getElementById(\"lanlist\");
                while (lanlist.rows.length > 0)
                        lanlist.deleteRow(0);
                for(i = 0; i < d.length; i++) {
                        e = lanlist.insertRow(-1);
                        if (d[i].disabled == \"disable\" || d[i].standby == \"yes\")
                                e.id = \"row4\";
                        else
                                e.id = \"row1\";
                        col = e.insertCell(0);
                        col.setAttribute('align', 'left');
                        col.setAttribute('width', '90');
			if (d[i].standby == \"yes\")
                        	col.innerHTML = \"<a style=color:#00ff00 href=javascript:showProxy(\" +
                                	\"'\" + d[i].name + \"')\" + \">\" + d[i].name + \"</a>\";
			else
                        	col.innerHTML = \"<a href=javascript:showProxy(\" +
                                	\"'\" + d[i].name + \"')\" + \">\" + d[i].name + \"</a>\";
                        col = e.insertCell(1);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '40');
                        col.innerHTML = \"<a href=javascript:ifShow(\" +
                                \"'\" + d[i].ifname + \"')\" + \">\" + d[i].ifname + \"</a>\";
                        col = e.insertCell(2);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '40');
                        if (d[i].linkup == \"1\")
                                col.innerHTML = \"<img src=/img/yes.png style=margin-right:5px;vertical-align:middle; />\";
                        else
                                col.innerHTML = \"<img src=/img/no.png style=margin-right:5px;vertical-align:middle; />\";
                        col= e.insertCell(3);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '100');
                        col.innerHTML = d[i].addr;
                        col= e.insertCell(4);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '70');
                        col.innerHTML = d[i].inbps;
                        col= e.insertCell(5);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '*');
                        col.innerHTML = d[i].outbps;
                }
                setTimeout(getLanList, 4065);
        }});
}
function getPxyList()
{
        AJXS({
            type: 'POST',
            url: '/cgi-bin/Monitor/ajax_pxylist',
            error: function(status){setTimeout(getPxyList, 4000);},
            success: function(data){
                var d;
                try {
                        d = eval('(' + data + ')');
                }catch(e) {
                        d = undefined;
                }
                if(typeof(d) == \"undefined\") {
                        setTimeout(getPxyList, 1000);
                        return;
                }
                var e, i;
                var lanlist = document.getElementById(\"pxylist\");
                while (lanlist.rows.length > 0)
                        lanlist.deleteRow(0);
                for(i = 1; i < d.length; i++) {
                        e = lanlist.insertRow(-1);
                        if (d[i].disabled == \"disable\" || d[i].standby == \"yes\")
                                e.id = \"row4\";
                        else
                                e.id = \"row1\";
                        col = e.insertCell(0);
                        col.setAttribute('align', 'left');
                        col.setAttribute('width', '90');
			if (d[i].standby == \"yes\")
                        	col.innerHTML = \"<a style='color:#00ff00' href=javascript:showProxy(\" +
                                	\"'\" + d[i].name + \"')\" + \">\" + d[i].name + \"</a>\";
			else
                        	col.innerHTML = \"<a href=javascript:showProxy(\" +
                                	\"'\" + d[i].name + \"')\" + \">\" + d[i].name + \"</a>\";
                        col = e.insertCell(1);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '40');
                        col.innerHTML = \"<a href=javascript:ifShow(\" +
                                \"'\" + d[i].ifname + \"')\" + \">\" + d[i].ifname + \"</a>\";
                        col = e.insertCell(2);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '40');
                        if (d[i].linkup == \"1\")
                                col.innerHTML = \"<img src=/img/yes.png style=margin-right:5px;vertical-align:middle; />\";
                        else
                                col.innerHTML = \"<img src=/img/no.png style=margin-right:5px;vertical-align:middle; />\";
                        col= e.insertCell(3);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '100');
                        col.innerHTML = d[i].addr;
                        col= e.insertCell(4);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '70');
                        col.innerHTML = d[i].inbps;
                        col= e.insertCell(5);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '*');
                        col.innerHTML = d[i].outbps;
                }
                setTimeout(getPxyList, 4137);
        }});
}
function getInfoGroup()
{
        AJXS({
            type: 'POST',
            url: '/cgi-bin/Monitor/ajax_infogroup',
            error: function(status){setTimeout(getInfoGroup, 4000);},
            success: function(data){
                var d;
                try {
                        d = eval('('+data+')');
                }catch(e) {
                        d = undefined;
                }
                if(typeof(d) == \"undefined\") {
                        setTimeout(getInfoGroup, 1000);
                        return;
                }
                var e, i;
                var list = document.getElementById(\"infogroup\");
                while (list.rows.length > 0)
                        list.deleteRow(0);
                for(i = 0; i < d.length; i++) {
			if (d[i].name == \"total\") {
				document.getElementById(\"totalup\").innerText = d[i].upbps;
				document.getElementById(\"totaldown\").innerText = d[i].downbps;
				continue;
			}
                        e = list.insertRow(-1);
			e.id = \"row1\";
                        col = e.insertCell(0);
                        col.setAttribute('align', 'left');
                        col.setAttribute('width', '120');
                        col.innerHTML = \"<a href=javascript:groupView(\" +
                                \"'\" + d[i].name + \"')\" + \">\" + d[i].cname + \"</a>\";
                        col = e.insertCell(1);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '80');
			col.innerText = d[i].flowcnt;
                        col = e.insertCell(2);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '80');
			col.innerText = d[i].upbps;
                        col = e.insertCell(3);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '80');
			col.innerText = d[i].downbps;
                        col = e.insertCell(4);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '*');
			col.innerText = d[i].per;
		}
                setTimeout(getInfoGroup, 4117);
	}});
}
function getTopApp()
{
        AJXS({
            type: 'POST',
            url: '/cgi-bin/Monitor/ajax_topapp',
            error: function(status){setTimeout(getTopApp, 4000);},
            success: function(data){
                var d;
                try {
                        d = eval('('+data+')');
                }catch(e) {
                        d = undefined;
                }
                if(typeof(d) == \"undefined\") {
                        setTimeout(getTopApp, 1000);
                        return;
                }
                var e, i;
                var list = document.getElementById(\"topapp\");
                while (list.rows.length > 0)
                        list.deleteRow(0);
                for(i = 0; i < d.length; i++) {
                        e = list.insertRow(-1);
			e.id = \"row1\";
                        col = e.insertCell(0);
                        col.setAttribute('align', 'left');
                        col.setAttribute('width', '120');
                        col.innerHTML = \"<a href=javascript:appShow(\" +
                                \"'\" + d[i].name + \"')\" + \">\" + d[i].cname + \"</a>\";
                        col = e.insertCell(1);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '100');
			col.innerText = d[i].flowcnt;
                        col = e.insertCell(2);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '100');
			col.innerText = d[i].upbps;
                        col = e.insertCell(3);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '*');
			col.innerText = d[i].downbps;
		}
                setTimeout(getTopApp, 4013);
	}});
}
function getTopIp()
{
        AJXS({
            type: 'POST',
            url: '/cgi-bin/Monitor/ajax_topip',
            error: function(status){setTimeout(getTopIp, 4000);},
            success: function(data){
                var d;
                try {
                        d = eval('('+data+')');
                }catch(e) {
                        d = undefined;
                }
                if(typeof(d) == \"undefined\") {
                        setTimeout(getTopIp, 1000);
                        return;
                }
                var e, i;
                var list = document.getElementById(\"topip\");
                while (list.rows.length > 0)
                        list.deleteRow(0);
                for(i = 0; i < d.length; i++) {
                        e = list.insertRow(-1);
			e.id = \"row1\";
                        col = e.insertCell(0);
                        col.setAttribute('align', 'left');
                        col.setAttribute('width', '120');
                        col.innerHTML = \"<a href=javascript:ipShow(\" +
                                \"'\" + d[i].ip + \"')\" + \">\" + d[i].ip+ \"</a>\";
                        col = e.insertCell(1);
                        col.setAttribute('align', 'left');
                        col.setAttribute('width', '120');
			col.innerText = d[i].mac;
                        col = e.insertCell(2);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '80');
			col.innerText = d[i].inbps;
                        col = e.insertCell(3);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '*');
			col.innerText = d[i].outbps;
		}
                setTimeout(getTopIp, 3997);
	}});
}
function getTopFlow()
{
        AJXS({
            type: 'POST',
            url: '/cgi-bin/Monitor/ajax_topflow',
            error: function(status){setTimeout(getTopFlow, 4000);},
            success: function(data){
                var d;
                try {
                        d = eval('('+data+')');
                }catch(e) {
                        d = undefined;
                }
                if(typeof(d) == \"undefined\") {
                        setTimeout(getTopFlow, 1000);
                        return;
                }
                var e, i;
                var list = document.getElementById(\"topflow\");
                while (list.rows.length > 0)
                        list.deleteRow(0);
                for(i = 0; i < d.length; i++) {
                        e = list.insertRow(-1);
			e.id = \"row1\";
                        col = e.insertCell(0);
                        col.setAttribute('align', 'left');
                        col.setAttribute('width', '120');
                        col.innerHTML = \"<a href=javascript:ipShow(\" +
                                \"'\" + d[i].ip + \"')\" + \">\" + d[i].ip+ \"</a>\";
                        col = e.insertCell(1);
                        col.setAttribute('align', 'left');
                        col.setAttribute('width', '120');
			col.innerText = d[i].mac;
                        col = e.insertCell(2);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '*');
			col.innerText = d[i].flowcnt;
		}
                setTimeout(getTopFlow, 4173);
	}});
}
function getSystem()
{
        AJXS({
            type: 'POST',
            url: '/cgi-bin/Monitor/ajax_system',
            error: function(status){setTimeout(getSystem, 4000);},
            success: function(data){
                var d;
                try {
                        d = eval('('+data+')');
                }catch(e) {
                        d = undefined;
                }
                if(typeof(d) == \"undefined\") {
                        setTimeout(getSystem, 1000);
                        return;
                }
		if (d.length > 0) {
			document.getElementById(\"runtime\").innerText = d[0].runtime;
			document.getElementById(\"totalmem\").innerText = d[0].totalmem;
			document.getElementById(\"memrate\").innerText = d[0].memrate;
			document.getElementById(\"cpu\").innerText = d[0].cpurate;
			document.getElementById(\"temperature\").innerText = d[0].temperature;
			document.getElementById(\"ipcnt\").innerText = d[0].ipcnt;
			document.getElementById(\"flowcnt\").innerText = d[0].flowcnt;
			document.getElementById(\"pps\").innerText = d[0].pps;
			document.getElementById(\"sigdb\").innerText = d[0].sigdb;
		}
                setTimeout(getSystem, 3300);
	}});
}
function onsize()
{
	var divGroup = document.getElementById(\"divGroup\");
	var divTopApp = document.getElementById(\"divTopApp\");
	var divTopIp = document.getElementById(\"divTopIp\");
	var divTopFlow = document.getElementById(\"divTopFlow\");
	
	if (document.body.clientWidth > 1500) {
		divGroup.style.left = \"902px\";
		divGroup.style.top  = \"15px\";
		divTopApp.style.left = \"0px\";
		divTopApp.style.top  = \"410px\";
		divTopIp.style.left  = \"451px\";
		divTopIp.style.top   = \"410px\";
		divTopFlow.style.left = \"902px\";
		divTopFlow.style.top = \"410px\";
	}
	else {
		divGroup.style.left = \"0px\";
		divGroup.style.top  = \"410px\";
		divTopApp.style.left = \"450px\";
		divTopApp.style.top  = \"410px\";
		divTopIp.style.left  = \"0px\";
		divTopIp.style.top   = \"780px\";
		divTopFlow.style.left = \"451px\";
		divTopFlow.style.top = \"780px\";
	}
}
function onloaddoc()
{
	getSystem();
	getPxyList();
	getInfoGroup();
	getTopApp();
	getTopIp();
	getTopFlow();
}
</script>
<body onload=\"onloaddoc()\" onresize=\"onsize()\">
<div id=divSystem style=\"position:absolute;padding:0px 5px 0px 5px;left:0;top:15;height:360px;width:430\">
<table style=\"width:430px; font-bold:true; font-size:13px; color:#CE6C04;border-bottom:1px dotted #185a73\">
<tr>
<td align=left><b>系统信息</b></td>
<td align=right><a href=\"javascript:infoSystem()\">More</a></td>
</tr>
</table>
<table width=\"430px\" border=0 cellspacing=1 cesspadding=1>
<tr id=row1>
<td width=100 align=left>系统名称</td>
<td align=left>${SYSNAME}</td>
</tr>
<tr id=row1>
<td width=100 align=left>当前时间</td>
<td align=left><a href=\"javascript:dateConfig()\">`date \"+%Y/%m/%d %H:%M:%S\"`</a>&nbsp[已运行<a id=runtime></a>]</td>
</tr>
<tr id=row1>
        <td align=left>CPU/内存</td>
        <td align=left>
		使用率:&nbsp;<a id=cpu></a>%&nbsp;&nbsp;
		温度:&nbsp;<a id=temperature>${temperature}</a>°C
		&nbsp;/&nbsp;<a id=totalmem></a>M,已使用<a id=memrate></a>%
	</td>
</tr>
<tr id=row1>
        <td align=left>网络概况</td>
        <td align=left>
		用户:&nbsp;<a id=ipcnt></a>&nbsp;
		连接:&nbsp;<a id=flowcnt></a>&nbsp;
		PPS:&nbsp;<a id=pps></a>&nbsp;
                上行:&nbsp;<a id=totalup></a>&nbsp;下行:&nbsp;<a id=totaldown></a>
	</td>
</tr>
</table>
<br>
<table style=\"width:430px; font-bold:true; font-size:13px; color:#CE6C04;border-bottom:1px dotted #185a73\">
<tr>
<td width=100 align=left><b>软件信息</b></td>
<td align=right><a href=\"javascript:sysUpgrade()\">More</a></td>
</tr>
</table>
<table width=\"430px\" border=0 cellspacing=1 cesspadding=1>
<tr id=row1>
        <td width=100 align=left>软件版本</td>
        <td width=* align=left>BSD${freebsdver},&nbsp;${BUILDREL},创建于${BUILDDATE}</td>
</tr>
<tr id=row1>
        <td align=left>特&nbsp;征&nbsp;库</td>
        <td width=* align=left id=sigdb></td>
</tr>
</table>
<br>
<table style=\"width:430px; font-bold:true; font-size:13px; color:#CE6C04;border-bottom:1px dotted #185a73\">
<tr>
<td align=left><b>软件授权</b></td>
<td align=right><a href=\"javascript:licenseUpgrade()\">More</a></td>
</tr>
</table>
<table width=\"430px\" border=0 cellspacing=1 cesspadding=1>
"; 
        for nameval in `${FLOWEYE} key info`; do
                eval "${nameval}"
        done
        startm=${start}
        endtm=${end}
        skipdays=$(((${endtm} - ${startm}) / 86400))
        if [ ${startm} -ne 0 ]; then
                startm=`date -r ${startm} "+%Y-%m-%d"`
        fi
        if [ ${endtm} -ne 0 ]; then
                endtm=`date -r ${endtm} "+%Y-%m-%d"`
        fi
        if [ ${freeend} -ne 0 ]; then
                freeend=`date -r ${freeend} "+%Y-%m-%d"`
        fi

echo -n "
<tr id=row1>
<td width=100 align=left>授权编号</td>
<td align=left>${oem}</td>
</tr>
<tr id=row1>
<td width=100 align=left>软件参数</td>
<td align=left>连接数${flowcnt}，IP数${ipcnt}</td>
</tr>
<tr id=row1>
<td align=left>使用时间</td>
";
if [ ${skipdays} -ge 8000 ]; then
	echo "<td align=left>可永久使用LICENSE</td>"
else
	leftdays=$((${leftime} / 86400))
	echo "<td align=left>${startm}至${endtm}"
	if [ ${expired} -eq 1 ]; then
		echo "&nbsp;<a style=\"color:#ff0000\"><b>已过期,请续费</b></a>"
	else
		echo "&nbsp;<a style=\"color:#ff0000\"><b>${leftdays}天后到期!</a>"
	fi
	echo "</td>"
fi

echo -n "
</tr>
</table>
</div>
<div id=divProxy style=\"position:absolute;padding:0px 5px 0px 5px;left:451;top:15;height:360px;width:430\">
<table style=\"width:430px; font-bold:true; font-size:13px; color:#CE6C04;border-bottom:1px dotted #185a73\">
<tr>
<td align=left><b>接口线路</b></td>
<td width=* align=right><a href=\"javascript:showWans()\">More</a></td>
</tr>
</table>
<table width=\"430px\" border=0 cellspacing=1 cellpadding=1>
<tr style=\"font-size:11px\">
        <td width=90  align=left>名称</td>
        <td width=40  align=right>网卡</td>
        <td width=40  align=right>状态</td>
        <td width=100 align=right>IP</td>
        <td width=70  align=right>流入</td>
        <td width=*   align=right>流出</td>
</tr>
</table>
<table id=pxylist width=\"430px\" border=0 cellspacing=1 cellpadding=1>
</table>
</div>
<div id=divGroup style=\"position:absolute;padding:0px 5px 0px 5px;left:902;top:15;height:360px;width:430\">
<table style=\"width:440px; font-bold:true; font-size:13px; color:#CE6C04;border-bottom:1px dotted #185a73\">
<tr>
<td align=left><b>流量分布</b></td>
<td width=* align=right><a href=\"javascript:groupStat()\">More</a></td>
</tr>
</table>
<table width=\"430px\" border=0 cellspacing=1 cellpadding=1>
<tr style=\"font-size:11px\">
        <td width=120 align=left>名称</td>
        <td width=80  align=right>连接</td>
        <td width=80  align=right>上行</td>
        <td width=80  align=right>下行</td>
	<td width=*   align=right>占比%</td>
</tr>
</table>
<table id=infogroup width=\"430px\" border=0 cellspacing=1 cellpadding=1>
</table>
</div> 
<div id=divTopApp style=\"position:absolute;padding:0px 5px 0px 5px;left:0;top:410;height:300px;width:430\">
<table style=\"width:430px; font-bold:true; font-size:13px; color:#CE6C04;border-bottom:1px dotted #185a73\">
<tr>
	<td align=left><b>TOP应用</b></td>
	<td width=* align=right><a href=\"javascript:showApps()\">More</a></td>
</tr>
</table>
<table width=\"430px\" border=0 cellspacing=1 cellpadding=1>
<tr style=\"font-size:11px\">
        <td width=120 align=left>名称</td>
        <td width=100 align=right>连接</td>
        <td width=100 align=right>上行</td>
        <td width=*   align=right>下行</td>
</tr>
</table>
<table id=topapp width=\"430px\" border=0 cellspacing=1 cellpadding=1>
</table>
</div>
<div id=divTopIp style=\"position:absolute;padding:0px 5px 0px 5px;left:451;top:410;height:300px;width:430\">
<table style=\"width:430px; font-bold:true; font-size:13px; color:#CE6C04;border-bottom:1px dotted #185a73\">
<tr>
	<td align=left width=120><b>TOP用户</b></td>
	<td align=left width=130><input type=text id=ipaddr placeholder=\"用户IP\" style=\"width:95;height:18;\" />
	<a href=\"javascript:ipQuery()\">查询</a></td>
	<td width=* align=right><a href=\"javascript:showTopIps('allbps')\">More</a></td>
</tr>
</table>
<table width=\"430px\" border=0 cellspacing=1 cellpadding=1>
<tr style=\"font-size:11px\">
        <td width=120 align=left>IP</td>
        <td width=120 align=left>MAC</td>
        <td width=80  align=right>流入</td>
        <td width=*   align=right>流出</td>
</tr>
</table>
<table id=topip width=\"430px\" border=0 cellspacing=1 cellpadding=1>
</table>
</div>
<div id=divTopFlow style=\"position:absolute;padding:0px 5px 0px 5px;left:902;top:410;height:300px;width:430\">
<table style=\"width:430px; font-bold:true; font-size:13px; color:#CE6C04;border-bottom:1px dotted #185a73\">
<tr>
	<td align=left><b>TOP连接</b></td>
	<td width=* align=right><a href=\"javascript:showTopFlows('flowcnt')\">More</a></td>
</tr>
</table>
<table width=\"430px\" border=0 cellspacing=1 cellpadding=1>
<tr style=\"font-size:11px\">
        <td width=120 align=left>IP</td>
        <td width=120 align=left>MAC</td>
        <td width=*   align=right>连接</td>
</tr>
</table>
<table id=topflow width=\"430px\" border=0 cellspacing=1 cellpadding=1>
</table>
</div> 
</body>
</html>
";