#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n ""; 
. ../common/common.sh 
[ "${CGI_refresh}" = "" ] && CGI_refresh=0
[ "${CGI_topn}" = "" ] && CGI_topn="0"
[ "${CGI_statype}" = "" ] && CGI_statype="last"
[ "${CGI_bridge}" = "" ] && CGI_bridge="0"
cgipath="/cgi-bin/Monitor/`basename $0`"
CGI_title="`${FLOWEYE} app name ${CGI_group}`概览" 
cgiargs="title=${CGI_title}&refresh=${CGI_refresh}&statype=${CGI_statype}&topn=${CGI_topn}&group=${CGI_group}&bridge=${CGI_bridge}"
cgiurl="${cgipath}?${cgiargs}"
[ ${CGI_refresh} -ne 0 ] && afm_load_page  ${CGI_refresh} "${cgiurl}"

echo -n "
<script type=\"text/javascript\" src=\"/img/common.js\"></script>
<script language=\"javascript\">
function popupUrl(url, width, height) 
{
 	ShowWindow(url, \"scrollbars=1,resizable=0\", width, height);
}
function onSelected() 
{
        var count = 0;
        var apps = document.getElementsByName(\"appselect\");
        for (var i = 0; i < apps.length; i++) 
                if (apps[i].checked) count++;
        document.getElementsByName(\"showselect\")[0].disabled = count > 0 ? false : true;
}
function showSelected() 
{
	var i;
	var url;
	var apps;
	var datasrc;
	var statype;
	var title;
	datasrc=\"\";
	statype = document.getElementsByName(\"statype\")[0];
	apps = document.getElementsByName(\"appselect\");
	for (i = 0; i < apps.length; i++) {
		if (apps[i].checked) {
			if (statype.value == \"last\" || statype.value == \"all\") 
				datasrc = datasrc + \",\" + apps[i].value + \".bps\";
			else
			if (statype.value == \"bpsup\") 
				datasrc = datasrc + \",\" + apps[i].value + \".bpsout\";
			else
			if (statype.value == \"bpsdn\") 
				datasrc = datasrc + \",\" + apps[i].value + \".bpsin\";
			else
			if (statype.value == \"flow\") 
				datasrc = datasrc + \",\" + apps[i].value + \".flow\";
		}
	}
	if (statype.value == \"last\" || statype.value == \"all\") 
		title = \"流量趋势图\"
	else
	if (statype.value == \"bpsup\")
		title = \"上行流量趋势图\"
	else
	if (statype.value == \"bpsdn\")
		title = \"下行流量趋势图\"
	else
	if (statype.value == \"flow\")
		title = \"连接趋势图\"
	url = \"/cgi-bin/Monitor/appreport?bridge=${CGI_bridge}&datasrc=\" + datasrc + \"&title=\" + title;
 	ShowWindow(url, \"scrollbars=1,resizable=0\", 670, 850);
}
function showApp(appid, appname) 
{
	var url = \"/cgi-bin/Monitor/appview_topip?bridge=${CGI_bridge}&appid=\" + 
		appid + \"&appname=\" + appname;
 	ShowWindow(url, \"scrollbars=1,resizable=0\", 740, 800);
}
</script>
<body>
<script type=\"text/javascript\" src=\"/img/wz_tooltip.js\"></script>
<span id=\"hlp3day\" style=\"display:none\">查看最近三天趋势图</span>
<span id=\"hlpall\" style=\"display:none\">查看最近一周、一月的趋势图</span>
";
if [ ${CGI_bridge} -eq 0 ]; then
	cgi_show_title "${CGI_title}(系统)" 
else
	if [ "${CGI_vlinkname}" = "" ]; then
		cgi_show_title "${CGI_title}(网桥${CGI_bridge})"
	else
		cgi_show_title "${CGI_title}(${CGI_vlinkname})"
	fi
fi

echo -n "
<br>
<table width=\"1000\" border=0 cellspacing=1 cellpadding=1 bgcolor=\"#ffffff\">
<form method=post action=\"${cgipath}\">
<tr id=tblhdr height=22>
"; if [ "${CGI_vlinkname}" != "" ]; then 
echo -n "
	<td width=131 align=center>${CGI_vlinkname}<input type=hidden name=bridge value=\"${CGI_bridge}\" /></td>
"; else 
echo -n "
        <td width=151 align=left>网桥&nbsp;
        <select name=bridge value=\"${CGI_bridge}\" style=\"width:90\">";
                for bdg in 0 `${FLOWEYE} bridge list`; do
                        selected=""
                        [ ${bdg} -eq ${CGI_bridge} ] && selected="selected"
                        if [ ${bdg} -eq 0 ]; then
                                echo "<option value=${bdg} ${selected}>所有流量</option>"
                        else    
                                echo "<option value=${bdg} ${selected}>网桥${bdg}</option>"
                        fi
                done 
echo -n "
        </select>
        </td>   
"; fi 
echo -n "
	<td width=206 class=bgurl2 align=left>按照&nbsp;
        <select name=statype value=\"${CGI_statype}\" style=\"width:140\"> ";
		if [ "${CGI_statype}" = "last" ]; then
			echo "<option value=last selected>最近10分钟流量</option>"
		else
			echo "<option value=last>最近10分钟流量</option>"
		fi
		if [ "${CGI_statype}" = "all" ]; then
			echo "<option value=all selected>累计流量</option>"
		else
			echo "<option value=all>累计流量</option>"
		fi
		if [ "${CGI_statype}" = "bpsup" ]; then
			echo "<option value=bpsup selected>上行bps</option>"
		else
			echo "<option value=bpsup>上行bps</option>"
		fi
		if [ "${CGI_statype}" = "bpsdn" ]; then
			echo "<option value=bpsdn selected>下行bps</option>"
		else
			echo "<option value=bpsdn>下行bps</option>"
		fi 
		if [ "${CGI_statype}" = "flow" ]; then
			echo "<option value=flow selected>连接数</option>"
		else
			echo "<option value=flow>连接数</option>"
		fi 
		if [ "${CGI_statype}" = "natbpsup" ]; then
			echo "<option value=natbpsup selected>代理上行bps</option>"
		else
			echo "<option value=natbpsup>代理上行bps</option>"
		fi
		if [ "${CGI_statype}" = "natbpsdown" ]; then
			echo "<option value=natbpsdown selected>代理下行bps</option>"
		else
			echo "<option value=natbpsdown>代理下行bps</option>"
		fi
	
echo -n "
        </select>&nbsp;排序</td>
	<td width=262 class=bgurl2 align=left>显示前<select name=topn value=\"${CGI_topn}\" style=\"width:65\"> ";
		for tm in 10 20 30 50 100 0; do
			if [  ${tm} -eq 0 ]; then
				tmdesc="所有"
			else
				tmdesc="${tm}"
			fi
			if [ "${CGI_topn}" = "${tm}" ]; then
				echo "<option selected value=${tm}>${tmdesc}</option>"
			else
				echo "<option value=${tm}>${tmdesc}</option>"
			fi
		done 
echo -n "
	</select>项&nbsp;隔
	<select name=refresh value=\"${CGI_refresh}\" style=\"width:70\">
	";
		for tm in 15 30 45 60 100 0; do
			if [ ${tm} -eq 0 ]; then
				tmdesc="不刷新"
			else
				tmdesc="${tm}"
			fi
			if [ "${CGI_refresh}" = "${tm}" ]; then
				echo "<option selected value=${tm}>${tmdesc}</option>"
			else
				echo "<option value=${tm}>${tmdesc}</option>"
			fi
		done
	
echo -n "
	</select>&nbsp;秒刷新</td>
	<td width=* class=bgurl2 align=right>
		<input type=submit value=\"刷  新\" style=\"width:70\"></input>&nbsp;&nbsp;
		<input type=button name=showselect disabled value=\"选中应用对比分析\" style=\"width:120\" onclick=\"javascript:showSelected()\"></input>
		<input type=hidden name=title value=\"${CGI_title}\"></input>
		<input type=hidden name=group value=\"${CGI_group}\"></input>
	</td>
</tr>
</form>
</table>
";
urlpath="${cgipath}?title=${CGI_title}&bridge=${CGI_bridge}&topn=${CGI_topn}&refresh=${CGI_refresh}&group=${CGI_group}"

echo -n "
<table width=1000 border=0 cellspacing=1 cellpadding=2>
<tr id=tblhdr height=22>
	<td width=148 align=center>协议名称</td>
	<td width=70 align=center><a href=\"${urlpath}&statype=flow\">连接数</a></td>
	<td width=92 align=center><a href=\"${urlpath}&statype=bpsup\">上行bps</a></td>
	<td width=92 align=center><a href=\"${urlpath}&statype=bpsdn\">下行bps</a></td>
	<td width=98 align=center><a href=\"${urlpath}&statype=natbpsup\">代理上行bps</a></td>
	<td width=98 align=center><a href=\"${urlpath}&statype=natbpsdown\">代理下行bps</a></td>
	<td width=180 align=center><a href=\"${urlpath}&statype=all\">累计流量及百分比</a></td>
	<td width=* align=center><a href=\"${urlpath}&statype=last\">最近10分钟流量及百分比</a></td>
</tr>
";
args="sort=${CGI_statype} bridge=${CGI_bridge}"
[ ${CGI_topn} -ne 0 ] && args="${args} topn=${CGI_topn}"
idname="row1"
${FLOWEYE} app stat app=${CGI_group} ${args} showsum | \
while read appid appname flow node aup adown all per1 lup ldown lall per2 rup rdown rall natbpsup natbpsdown theother
do

echo -n "
	<tr id=${idname}>
"; if [ "${appid}" != "total" ]; then 
echo -n "
	<td align=left>&nbsp;<input type=checkbox name=appselect value=\"${appid}\" onclick=\"onSelected()\"></input>
	<a href=\"javascript:showApp('${appid}', '${appname}')\">${appname}</td>
"; else 
echo -n "
	<td align=center><b>合计</b></td>
"; fi 
echo -n "
	<td align=right>${flow}</td>
	<td align=right>${rup}</td>
	<td align=right>${rdown}</td>
	<td align=right>${natbpsup}</td>
	<td align=right>${natbpsdown}</td>
	"; wid=`echo "${per1}" | awk '{print ($1 * 90.00) / 100.00}'` 
echo -n "
	<td><table cellpading=0 cellspacing=0><tr id=row5><td width=62 align=right>${all}</td>
	<td align=left>&nbsp;<img src=\"/img/data_bar.gif\" width=${wid} height=10 alt=\"${per1}%\" border=0>&nbsp;${per1}</td>
	</tr></table></td>
	"; wid=`echo "${per2}" |awk '{print ($1 * 90.00) / 100.00}'` 
echo -n "
	<td><table cellpading=0 cellspacing=0><tr id=row5><td width=62 align=right>${lall}</td>
	<td align=left>&nbsp;<img src=\"/img/data_bar.gif\" width=${wid} height=10 alt=\"${per2}%\" border=0>&nbsp;${per2}</td>
	</tr></table></td>
	</tr>
"; 
	if [ "${idname}" = "row1" ]; then
		idname="row2"
	else
		idname="row1"
	fi
done

echo -n "
</table>
";
TMPPATH=${PGPATH}/admin/tmp
grpbps_up=${TMPPATH}/day_${CGI_group}_bps_${CGI_bridge}_up.png
grpbps_down=${TMPPATH}/day_${CGI_group}_bps_${CGI_bridge}_down.png
comargs="type=line bridge=${CGI_bridge} width=1000 height=240 hours=24"
errmsg=`${FLOWEYE} chart show ${comargs} outimg=${grpbps_up} tag=${CGI_group}.bpsout`
errmsg=`${FLOWEYE} chart show ${comargs} outimg=${grpbps_down} tag=${CGI_group}.bpsin`
grpflow=${TMPPATH}/day_${CGI_group}_flow_${CGI_bridge}.png
errmsg=`${FLOWEYE} chart show ${comargs} yname=#flow outimg=${grpflow} tag=${CGI_group}.flow`

echo -n "
<br>
<table style=\"width:1000; font-bold:true;font-size:15px; color:#CE6C04\">
<tr>
<td align=left><b>最近24小时上行流量趋势图</b></td>
<td align=right>
<a href=\"javascript:popupUrl('/cgi-bin/Monitor/grpgraph?group=${CGI_group}&bridge=${CGI_bridge}&type=bps&time=3day', 700, 800)\"
    onmouseover=\"TagToTip('hlp3day')\" onmouseout=\"UnTip()\">三日对比</a>
<a href=\"javascript:popupUrl('/cgi-bin/Monitor/grpgraph?group=${CGI_group}&bridge=${CGI_bridge}&type=bps&time=mon', 700, 800)\"
    onmouseover=\"TagToTip('hlpall')\" onmouseout=\"UnTip()\">历史图表</a>
</td>
</tr>
</table>
<table width=1000 border=0 cellspacing=1 cellpadding=1 bgcolor=\"#ffffff\">
<tr><td><img src=\"/tmp/day_${CGI_group}_bps_${CGI_bridge}_up.png\"></img></td></tr>
</table>
<br>
<table style=\"width:1000; font-bold:true;font-size:15px; color:#CE6C04\">
<tr>
<td align=left><b>最近24小时下行流量趋势图</b></td>
<td align=right>
<a href=\"javascript:popupUrl('/cgi-bin/Monitor/grpgraph?group=${CGI_group}&bridge=${CGI_bridge}&type=bps&time=3day', 700, 800)\"
    onmouseover=\"TagToTip('hlp3day')\" onmouseout=\"UnTip()\">三日对比</a>
<a href=\"javascript:popupUrl('/cgi-bin/Monitor/grpgraph?group=${CGI_group}&bridge=${CGI_bridge}&type=bps&time=mon', 700, 800)\"
    onmouseover=\"TagToTip('hlpall')\" onmouseout=\"UnTip()\">历史图表</a>
</td>
</tr>
</table>
<table width=1000 border=0 cellspacing=1 cellpadding=1 bgcolor=\"#ffffff\">
<tr><td><img src=\"/tmp/day_${CGI_group}_bps_${CGI_bridge}_down.png\"></img></td></tr>
</table>
<br>
<table style=\"width:1000; font-bold:true;font-size:15px; color:#CE6C04\">
<tr>
<td align=left><b>最近24小时连接趋势图</b></td>
<td align=right>
<a href=\"javascript:popupUrl('/cgi-bin/Monitor/grpgraph?group=${CGI_group}&bridge=${CGI_bridge}&type=flow&time=3day', 700, 800)\"
    onmouseover=\"TagToTip('hlp3day')\" onmouseout=\"UnTip()\">三日对比</a>
<a href=\"javascript:popupUrl('/cgi-bin/Monitor/grpgraph?group=${CGI_group}&bridge=${CGI_bridge}&type=flow&time=mon', 700, 800)\"
    onmouseover=\"TagToTip('hlpall')\" onmouseout=\"UnTip()\">历史图表</a>
</td>
</tr>
</table>
<table width=1000 border=0 cellspacing=1 cellpadding=1 bgcolor=\"#ffffff\">
<tr> <td><img src=\"/tmp/day_${CGI_group}_flow_${CGI_bridge}.png\"></img></td> </tr>
</table>
</body>
</html>
";