#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n "";
CGI_browsertitle="网卡调度"
. ../common/common.sh
for nameval in `${FLOWEYE} system stat | grep extflow`
do
	eval "${nameval}"
done

echo -n "
<script type=\"text/javascript\" src=\"/img/common.js\"></script>
<script language=\"javascript\">
function ifmap(name, queue) 
{
	var url = \"/cgi-bin/Monitor/ifmap?name=\" + name+ \"&queue=\" + queue;
	ShowWindow(url, \"\", 320, 100);
}
function ifView(ifname)
{
        var url = \"/cgi-bin/Monitor/if_show?name=\" + ifname + \"&title=网络接口->\" + ifname;
        ShowWindow(url, \"\", 720, 700);
}
function getpolicystats()
{
	var row;
	AJXS({type: 'POST', 
	       url: '/cgi-bin/Monitor/ajax_ifsched', 
	     error: function(status){setTimeout(getpolicystats, 4000);},
	   success: function(data) { 
		var d, i;
		var bpsobj;
		try {
			d = eval('('+data+')');
		} catch(e) {
			setTimeout(getpolicystats, 4000);
			return;
		}
		var totalpps = 0;
		for (i = 0; i < d.length; i++) {
			if (d[i].name == \"system\") {
				waitobj = document.getElementById(\"wait_\" + d[i].flow);
				burstobj = document.getElementById(\"burst_\" + d[i].flow);
				ppsobj = document.getElementById(\"pps_\" + d[i].flow);
				pktrejobj = document.getElementById(\"pktrej_\" + d[i].flow);
				if (waitobj != null) waitobj.innerHTML = d[i].wait + \"&nbsp;\";
				if (burstobj != null) burstobj.innerHTML = d[i].burst + \"&nbsp;\";
				if (ppsobj != null) ppsobj.innerHTML = d[i].pps + \"&nbsp;\";
				if (pktrejobj != null) pktrejobj.innerHTML = d[i].pktrej + \"&nbsp;\";
				totalpps += Number(d[i].pps);
			}
			else {
				ifmapflowobj = document.getElementById(\"ifmapflow_\" + d[i].name + \"_\" + d[i].wait);
				ifmapppsobj = document.getElementById(\"ifmappps_\" + d[i].name + \"_\" + d[i].wait);
				if (ifmapflowobj != null)
					ifmapflowobj.innerHTML = \"单元\" + d[i].flow + \"&nbsp;\";
				if (ifmapppsobj != null)
					ifmapppsobj.innerHTML = d[i].pps + \"&nbsp;\";
			}
		}
	
		document.getElementById(\"totalpps\").innerText = totalpps;	
		setTimeout(getpolicystats, 4000);
	}});
}
function onloaddoc()
{
	getpolicystats();
}
</script>
<body onload=\"onloaddoc()\">
<table style=\"width:480; font-bold:true;font-size:14px; color:#CE6C04\">
<tr><td align=left><b>核心列表[<a id=totalpps></a>]</b></td>
</table>
<table width=480 border=0 cellspacing=1 cellpadding=1>
<tr id=tblhdr>
        <td width=60 align=center>处理单元</td>
        <td width=90 align=right>等待包</td>
        <td width=90 align=right>突发值</td>
        <td width=90 align=right>PPS</td>
	<td width=90 align=right>拒绝服务</td>
</tr>
";
idname="row1"
${FLOWEYE} system list | while read flow cpu wait burst pps pktrejs theother
do 
	[ "${flow}" = "flow" ] && continue
	if [ "${flow}" = "0" ]; then
		unitname="备用单元"
	else
		unitname="单元${flow}"
	fi

echo -n "
	<tr id=${idname}>
	<td align=center>${unitname}</td>
	<td id=wait_${flow} align=right>${wait}</td>
	<td id=burst_${flow} align=right>${burst}</td>
	<td id=pps_${flow} align=right style=\"color:#0000ff\">${pps}</td>
	<td id=pktrej_${flow} align=right style=\"color:#ff0000\">${pktrejs}&nbsp;</td>
	</tr>
";
	if [ "${idname}" = "row1" ]; then
        	idname="row2"
	else
        	idname="row1"
	fi
done

echo -n "
</table>
<br> 
<table style=\"width:480; font-bold:true;font-size:14px; color:#CE6C04\">
<tr> <td align=left><b>网卡队列</b></td>
</table>
<table width=480 border=0 cellspacing=1 cellpadding=1>
<tr id=tblhdr>
        <td width=60 align=center>网卡</td>
        <td width=90 align=right>队列</td>
        <td width=90 align=right>处理单元</td>
        <td width=90 align=right>PPS</td>
        <td width=90 align=right>操作</td>
</tr> 
";
idname="row1"
${FLOWEYE} ifmap list | while read name queue autoflow setflow pps theother
do 
	[ "${name}" = "name" ] && continue

echo -n "
	<tr id=${idname} height=23>
	<td align=center><a style=\"color:#0000ff\" href=\"javascript:ifView('${name}')\">${name}</a></td>
	<td align=right>${queue}</td>
"; if [ "${setflow}" != "0" ]; then 
echo -n "
	<td id=ifmapflow_${name}_${queue} align=right>单元${setflow}</td>
"; else 
echo -n "
	<td id=ifmapflow_${name}_${queue} align=right>单元${autoflow}</td>
"; fi 
echo -n "
	<td id=ifmappps_${name}_${queue} align=right style=\"color:#0000ff\">${pps}</td>
	<td align=right><img src=\"/img/edit.png\" style=\"margin-top: 3px\" onclick=\"ifmap('${name}', '${queue}')\" title=\"修改策略\" />&nbsp;</td>
";
	if [ "${idname}" = "row1" ]; then
		idname="row2"
	else
		idname="row1"
	fi
done

echo -n "
</body>
</html>
";