#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n ""; 
CGI_browsertitle="${CGI_ipaddr}->移动终端"
. ../common/common.sh 
[ "${CGI_sort}" = "" ] && CGI_sort="bytes"
args="ipaddr=${CGI_ipaddr}&sort=${CGI_sort}"
MOD_TAB_LIST="流量概况#/cgi-bin/Monitor/ipview_data?${args} 连接信息#/cgi-bin/Monitor/ipview_flow?${args} 虚拟身份#/cgi-bin/Monitor/ipview_account?${args} 共享用户#/cgi-bin/Monitor/ipview_lip?${args} 移动终端#/cgi-bin/Monitor/ipview_mobile?${args}"
afm_load_page 30 "/cgi-bin/Monitor/ipview_mobile?${args}"
myself="/cgi-bin/Monitor/`basename $0`"
urlpath="${myself}?ipaddr=${CGI_ipaddr}"

echo -n "
<body>
";
for nameval in `${FLOWEYE} ipobj get ${CGI_ipaddr}`
do
        tag=`echo ${nameval} | cut -d'=' -f1`
        val=`echo ${nameval} | cut -d'=' -f2-`
        export ${tag}="${val}"
done
if [ ${usertype} -ne 0 ]; then
	MOD_TAB_LIST="${MOD_TAB_LIST} 账号信息#/cgi-bin/Monitor/ipview_usrinfo?${args}"
fi
cgi_show_ipobj_info 
cgi_print_mod_header "移动终端" 800

echo -n "
<table width=800 border=0 cellspacing=1 cellpadding=1> 
<tr id=tblhdr>
	<td width=50  align=center>序号</td>
	<td width=300 align=right>终端类型</td>
	<td width=*   align=right>最近访问</td>
</tr>
";
idname="row1"
no=1
${FLOWEYE} mobile list ip=${CGI_ipaddr} | \
while read ipaddr lastime name
do 
echo -n "
	<tr id=${idname}>
	<td align=center>${no}</td>
	<td align=right>${name}</td>
	<td align=right>${lastime}</td>
	</tr>
";
	if [ "${idname}" = "row1" ]; then
		idname="row2"
	else
		idname="row1"
	fi
	no=$((${no} + 1))
done

echo -n "
</table>
</body>
</html>
";