#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n ""; 
CGI_browsertitle="${CGI_ipaddr}->连接信息"
. ../common/common.sh 
[ "${CGI_sort}" = "" ] && CGI_sort="bytes"
args="ipaddr=${CGI_ipaddr}&sort=${CGI_sort}"
MOD_TAB_LIST="流量概况#/cgi-bin/Monitor/ipview_data?${args} 连接信息#/cgi-bin/Monitor/ipview_flow?${args} 虚拟身份#/cgi-bin/Monitor/ipview_account?${args} 共享用户#/cgi-bin/Monitor/ipview_lip?${args} 移动终端#/cgi-bin/Monitor/ipview_mobile?${args}"
myself="/cgi-bin/Monitor/`basename $0`"
urlpath="${myself}?ipaddr=${CGI_ipaddr}"

echo -n "
<script type=\"text/javascript\" src=\"/img/common.js\"></script>
<script language=\"javascript\">
function showProxy(proxyname)
{
        var url = \"/cgi-bin/Monitor/proxy_show?proxyname=\" + proxyname;
        ShowWindow(url, \"\", 350, 400);
}
</script>
<body>
";
for nameval in `${FLOWEYE} ipobj get ${CGI_ipaddr}`
do
        tag=`echo ${nameval} | cut -d'=' -f1`
        val=`echo ${nameval} | cut -d'=' -f2-`
        export ${tag}="${val}"
done
if [ ${usertype} -ne 0 ]; then
	MOD_TAB_LIST="${MOD_TAB_LIST} 账号信息#/cgi-bin/Monitor/ipview_usrinfo?${args}"
fi

echo -n "
"; cgi_show_ipobj_info 
echo -n "
"; cgi_print_mod_header "连接信息" 800 
echo -n "
<table width=100% border=0 cellspacing=1 cellpadding=1> 
<tr id=tblhdr>
	<td width=70  align=left><a href=\"${urlpath}&sort=app\">应用名称</a></td>
	<td width=30  align=left><a href=\"${urlpath}&sort=proto\">协议</a></td>
	<td width=80  align=right>首包接口</td>
	<td width=160 align=right><a href=\"${urlpath}&sort=dst\">连接</a>[<a style=\"color:#ff0000\">红色表示被拒绝</a>]</td>
	<td width=70  align=right><a href=\"${urlpath}&sort=dst\">WAN线路</a></td>
	<td width=40  align=right><a href=\"${urlpath}&sort=time\">时长</a></td>
	<td width=35  align=right>DSCP</td>
	<td width=100 align=right><a href=\"${urlpath}&sort=bytes\">流量(up/down)</a></td>
	<td width=*   align=right><a href=\"${urlpath}&sort=host\">其它信息</a></td>
</tr>
";
idname="row1"
${FLOWEYE} ipobj listflow2 ${CGI_ipaddr} ${CGI_appid} -s ${CGI_sort}| \
while read life appname tcpudp conninfo bytes1 bytes2 ttl allbytes clpdeny tos1 tos2 proxyname host ifname inpxyname theothers
do
	[ "${proxyname}" = "NULL" ] && proxyname=""
	[ "${host}" = "NULL" ] && host=""
	if [ ${clpdeny} -eq 1 ]; then 

echo -n "
		<tr id=${idname}>
		<td align=left style=\"color:#ff0000\">&nbsp;${appname}</td>
		<td align=rightstyle=\"color:#ff0000\">${tcpudp}</td>
		<td></td>
		<td align=right style=\"color:#ff0000\">${conninfo}</td>
		<td align=right><a style=\"color:#0000ff\" href=\"javascript:showProxy('${proxyname}')\">${proxyname}</a></td>
		<td align=right style=\"color:#ff0000\">${life}</td>
		<td align=right style=\"color:#ff0000\">${tos1}/${tos2}</td>
		<td align=right style=\"color:#ff0000\">${bytes1}/${bytes2}</td>
		<td align=right>${host}</td>
		</tr>
";	else 
echo -n "
		<tr id=${idname}>
		<td align=left>${appname}</td>
		<td align=left>${tcpudp}</td>
		<td align=right>${ifname}/${inpxyname}</td>
		<td align=right>${conninfo}</td>
		<td align=right><a style=\"color:#0000ff\" href=\"javascript:showProxy('${proxyname}')\">${proxyname}</a></td>
		<td align=right>${life}</td>
		<td align=right>${tos1}/${tos2}</td>
		<td align=right>${bytes1}/${bytes2}</td>
		<td align=right>${host}</td>
		</tr>
"; 	fi
	if [ "${idname}" = "row1" ]; then
		idname="row2"
	else
		idname="row1"
	fi
done

echo -n "
</table>
</body>
</html>
";