#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n ""; 
CGI_browsertitle="${CGI_ipaddr}->流量概况"
. ../common/common.sh 
args="ipaddr=${CGI_ipaddr}"
MOD_TAB_LIST="流量概况#/cgi-bin/Monitor/ipview_data?${args} 连接信息#/cgi-bin/Monitor/ipview_flow?${args} 虚拟身份#/cgi-bin/Monitor/ipview_account?${args} 共享用户#/cgi-bin/Monitor/ipview_lip?${args} 移动终端#/cgi-bin/Monitor/ipview_mobile?${args}"

echo -n "
<script type=\"text/javascript\" src=\"/img/common.js\"></script>
<script language=\"javascript\">
function ipDetail()
{
        AJXS({
            type: 'POST',
           url: '/cgi-bin/Monitor/ajax_ipview_detail?ip=${CGI_ipaddr}',
            error: function(status){setTimeout(ipDetail, 4000);},
            success: function(data){
                var d;
                try {
                        d = eval('('+data+')');
                }catch(e) {
                        d = undefined;
                }
                if(typeof(d) == \"undefined\") {
                        setTimeout(ipDetail, 1000);
                        return;
                }
		if (d.length > 0) {
			document.getElementById(\"ipoutbytes\").innerText = d[0].outbytes;
			document.getElementById(\"ipinbytes\").innerText = d[0].inbytes;
			document.getElementById(\"ipbpsout\").innerText = d[0].bpsout;
			document.getElementById(\"ipbpsin\").innerText = d[0].bpsin;
			document.getElementById(\"iplifetime\").innerText = d[0].life_tmstr;
			document.getElementById(\"ipflowcnt\").innerText = d[0].flowcnt;
			document.getElementById(\"ipqqcnt\").innerText = d[0].qqcnt + \"/\" + d[0].accountcnt;
			document.getElementById(\"ipqqcnt\").innerText = d[0].qqcnt + \"/\" + d[0].accountcnt;
			document.getElementById(\"ipmstcnt\").innerText = d[0].mstcnt;
		}
                setTimeout(ipDetail, 4000);
        }});
}
function ipAppList()
{
        AJXS({
            type: 'POST',
           url: '/cgi-bin/Monitor/ajax_ipview_applist?ip=${CGI_ipaddr}',
            error: function(status){setTimeout(ipAppList, 4000);},
            success: function(data){
                var d;
                try {
                        d = eval('('+data+')');
                }catch(e) {
                        d = undefined;
                }
                if(typeof(d) == \"undefined\") {
                        setTimeout(ipAppList, 1000);
                        return;
                }
                var e, i;
                var cname, upbps, downbps, allbps;
                var list = document.getElementById(\"applist\");
                while (list.rows.length > 0)
                        list.deleteRow(0);
                for(i = 0; i < d.length; i++) {
                        e = list.insertRow(-1);
                        e.id = \"row1\";
                        col = e.insertCell(0);
                        col.setAttribute('align', 'center');
                        col.setAttribute('width', '50');
			col.innerText = i + 1;
                        col = e.insertCell(1);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '180');
			col.innerText = d[i].cname;
                        col = e.insertCell(2);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '180');
			col.innerText = d[i].inbps;
                        col = e.insertCell(3);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '180');
			col.innerText = d[i].outbps;
                        col = e.insertCell(4);
                        col.setAttribute('align', 'right');
                        col.setAttribute('width', '*');
                        col.innerHTML = d[i].allbps;
                }
                setTimeout(ipAppList, 4000);
        }});
}
function onloaddoc()
{
	ipDetail();
	ipAppList();
}
</script>
<body onload=\"onloaddoc()\">
";
for nameval in `${FLOWEYE} ipobj get ${CGI_ipaddr}`
do
	tag=`echo ${nameval} | cut -d'=' -f1`
	val=`echo ${nameval} | cut -d'=' -f2-`
	export ${tag}=${val}
done
if [ ${usertype} -ne 0 ]; then
	MOD_TAB_LIST="${MOD_TAB_LIST} 账号信息#/cgi-bin/Monitor/ipview_usrinfo?${args}"
fi

echo -n "
"; cgi_show_ipobj_info 
echo -n "
"; cgi_print_mod_header "流量概况" 803 
echo -n "
<table width=\"803\" border=0 cellspacing=1 cellpadding=1> 
<tr id=tblhdr>
	<td width=50  class=bgurl1 align=center><b>序号</b></td>
	<td width=180  class=bgurl1 align=right><b>协议</b></td>
	<td width=180 class=bgurl1 align=right><b>流入速率</b></td>
	<td width=180 class=bgurl1 align=right><b>流出速率</b></td>
	<td width=*  class=bgurl1 align=right><b>总速率</b></td>
</tr>
</table>
<table id=applist width=\"803\" border=0 cellspacing=1 cellpadding=1>
</table>
</body>
</html>
";