#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n "";
. ../common/common.sh 
myself="/cgi-bin/Setup/`basename $0`"

echo -n "
<script type=\"text/javascript\" src=\"/img/common.js\"></script>
<script language=\"javascript\">
function beforeAddBWO(frm)
{
	var pname = document.getElementsByName(\"pname\")[0];
	var prate = document.getElementsByName(\"prate\")[0];
	pname.value = TrimAll(pname.value);
	if (!IsName(pname.value)) {
		alert(\"通道名称不能出现&等特殊字符!\");
		pname.select();
		return false;
	}
	prate.value = TrimAll(prate.value);
	if (prate.value == \"\") {
		alert(\"请输入带宽!\");
		prate.select();
		return false;
	}
	if (!IsDigitIn(prate.value, 1, 10000000)) {
		alert(\"带宽必须介于1kb/s和10000000kb/s之间!\");
		prate.select();
		return false;
	}
	return true;
}
function onCancel()
{
	window.location.href = \"/cgi-bin/Setup/pipe_list\";
}
</script>
";
if [ "${REQUEST_METHOD}" = "POST" ]; then
	operator_check "${myself}"
	if [ "${CGI_path}" = "" ]; then
		CGI_bridge=0
		CGI_dir="both"
	else
		CGI_bridge=`echo ${CGI_path} | cut -d'.' -f1`
		CGI_dir=`echo ${CGI_path} | cut -d'.' -f2`
	fi
	errmsg=`${FLOWEYE} policy addbwo name=${CGI_pname} rate=${CGI_rate}`
	if [ "$?" != "0" ]; then
		afm_dialog_msg "操作失败:${errmsg}"
	else
		afm_load_page 0 "/cgi-bin/Setup/pipe_list"
		exit 0
	fi
fi

echo -n "
<body>
"; cgi_show_title "策略对象->数据通道->添加数据通道" 
echo -n "
<br>
<form method=post onsubmit=\"return beforeAddBWO(this)\" action=\"${myself}\">
<table style=\"font:14px\" width=600 border=0 cellspacing=0 cellpadding=3 bgcolor=\"#ffffff\">
<tr id=row1>
	<td width=40></td>
        <td width=80 align=left>通道名称</td>
	<td width=400 align=left>
		<input type=text name=pname style=\"width:120px\" value=\"${CGI_pname}\"></input>
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>通道带宽</td>
        <td align=left>
		<input type=text name=rate style=\"width:120px\" value=\"${CGI_rate}\"></input> (单位:kbits/s 范围:1~10000000) 
	</td>
</tr>
</table>
<table style=\"width:600; border-bottom:1px #787882 solid; color:#0000ff\">
<tr><td align=right>&nbsp;</td></tr>
</table>
<table style=\"width:600\"> 
<tr>
        <td align=right>
		<input type=submit style=\"width:80\" value=\"提交\"></input>
		<input type=button style=\"width:80\" value=\"取消\" onclick=\"onCancel()\"></input>
	</td>
</tr>
</table>
</form>
</body>
</html>
";