#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n "";
. ../common/common.sh 
myself="/cgi-bin/Setup/`basename $0`"

echo -n "
<script type=\"text/javascript\" src=\"/img/common.js\"></script>
<script language=\"javascript\">
function beforeAddRule(frm)
{
	var rngs;
	var polno   = document.getElementsByName(\"polno\")[0];
	var intype  = document.getElementsByName(\"intype\")[0];
	var inipnet = document.getElementsByName(\"inipnet\")[0];
	var iniprng = document.getElementsByName(\"iniprng\")[0];
	var action  = document.getElementsByName(\"action\")[0];
	var actarg  = document.getElementsByName(\"actarg\")[0];
	polno.value = TrimAll(polno.value);
	if (!IsDigitIn(polno.value, 1, 65535)) {
		alert(\"规则序号必须是介于1和65535之间的一个整数!\");
		polno.select();
		return false;
	}
	inipnet.value = TrimAll(inipnet.value);
	iniprng.value = TrimAll(iniprng.value);
	if (intype.value == \"net\") {
		if (!IsIPAddr(inipnet.value)) {
			alert(\"请输入正确的IP地址，格式为x.x.x.x/n\");
			inipnet.select();
			return false;
		}
	}
	else
	if (intype.value == \"range\") {
		rngs = iniprng.value.split(\"-\");
		if (rngs.length != 2 || !IsIPAddr(rngs[0]) || !IsIPAddr(rngs[1])) {
			alert(\"请输入正确的IP段，格式为x.x.x.x-y.y.y.y\");
			iniprng.select();
			return false;
		}
	}
	actarg.value = TrimAll(actarg.value);
	if (actarg.value == \"\") {
		if (action.value == \"prompt\") {
			alert(\"请输入要提示的信息内容!\");
			return false;
		}
		else
		if (action.value == \"redirect\") {
			alert(\"请输入转向到的URL地址!\");
			return false;
		}
		else
		if (action.value == \"reqfwd\") {
			alert(\"请输入目标MAC地址!\");
			return false;
		}
	}
	return true;
}
function onCancel(polgrpid)
{
	window.location.href = \"/cgi-bin/Setup/urlfilter_getgrp?policy=\" + polgrpid;
}
function onIntypeChanged(obj)
{
	var net = document.getElementsByName(\"inipnet\")[0];
	var rng = document.getElementsByName(\"iniprng\")[0];
	var tbl = document.getElementsByName(\"iniptbl\")[0];
	if (obj.value == \"any\") {
		net.style.display = \"none\";
		rng.style.display = \"none\";
		tbl.style.display = \"none\";
	}
	else
	if (obj.value == \"net\") {
		net.style.display = \"block\";
		rng.style.display = \"none\";
		tbl.style.display = \"none\";
	}
	else
	if (obj.value == \"range\") {
		net.style.display = \"none\";
		rng.style.display = \"block\";
		tbl.style.display = \"none\";
	}
	else
	if (obj.value == \"table\") {
		net.style.display = \"none\";
		rng.style.display = \"none\";
		tbl.style.display = \"block\";
	}
}
function onActionChanged(obj)
{
	var outpxy = document.getElementsByName(\"outpxy\")[0];
	var actarg = document.getElementsByName(\"actarg\")[0];
	var actargname = document.getElementById(\"actargname\");
	if (obj.value == \"accept\" || obj.value == \"deny\") {
		outpxy.disabled = true; 
		actarg.disabled = true; 
	}
	else
	if (obj.value == \"redirect\") {
		outpxy.disabled = false; 
		actarg.disabled = false; 
		actargname.innerText = \"目标URL\";
	}
	else
	if (obj.value == \"prompt\") {
		outpxy.disabled = false; 
		actarg.disabled = false; 
		actargname.innerText = \"提示信息\";
	}
	else
	if (obj.value == \"reqfwd\") {
		outpxy.disabled = false; 
		actarg.disabled = true;
	} 
}
function onInit()
{
	var act = document.getElementsByName(\"action\")[0];
	onActionChanged(act);
}
</script>
";
if [ "${REQUEST_METHOD}" = "POST" ]; then
	operator_check "/cgi-bin/Setup/urlfilter_getgrp?policy=${CGI_policy}"
	case "${CGI_intype}" in
	"any")
		CGI_inip="any"
		;;
	"net")
		CGI_inip="${CGI_inipnet}"
		;;
	"range")
		CGI_inip="${CGI_iniprng}"
		;;
	"table")
		CGI_inip="${CGI_iniptbl}"
		;;
	esac
	[ "${CGI_natip}" = "" ] && CGI_natip="0"
	[ "${CGI_hasms}" = "" ] && CGI_hasms="0"
	[ "${CGI_qqcnt}" = "" ] && CGI_qqcnt="0"
	[ "${CGI_outpxy}" = "" ] && CGI_outpxy="NULL"
	cmdargs="group=${CGI_policy} id=${CGI_polno} inip=${CGI_inip}"
	cmdargs="${cmdargs} method=${CGI_method} ext=${CGI_ext} dns=${CGI_dns}"
	cmdargs="${cmdargs} natip=${CGI_natip} hasms=${CGI_hasms} onlyfirst=${CGI_onlyfirst}"
	cmdargs="${cmdargs} outpxy=${CGI_outpxy} action=${CGI_action}"
	[ "${CGI_actarg}" != "" ] && cmdargs="${cmdargs} actarg=${CGI_actarg}"
	errmsg=`${FLOWEYE} urlfilter addrule ${cmdargs}`
	if [ "$?" != "0" ]; then
		afm_dialog_msg "出现错误:${errmsg}"
	else
		WEB_LOGGER "添加HTTP管控策略" "grp=${CGI_policy},id=${CGI_polno}"
		afm_load_page 0 "/cgi-bin/Setup/urlfilter_getgrp?policy=${CGI_policy}"
		exit 0
	fi
else
	[ "${CGI_onlyfirst}" = "" ] && CGI_onlyfirst=0
	[ "${CGI_hasms}" = "" ] && CGI_hasms=0
fi

echo -n "
<body onload=\"onInit()\">
<script type=\"text/javascript\" src=\"/img/wz_tooltip.js\"></script>
<span id=\"hlpno\" style=\"display:none\">编号范围为1~65535,序号小的规则优先匹配</span>
<span id=\"hlpflow\" style=\"display:none\">范围为0~65535,不填或填入0表示没有限制</span>
<span id=\"hlpnatip\" style=\"display:none\">通过此IP共享上网的最小用户数，0表示忽略</span>
<span id=\"hlpactarg\" style=\"display:none\">请输入要提示的信息或要重定向的URL,或目标MAC地址</span>
";
policyname=`${FLOWEYE} urlfilter listgrp | grep "^${CGI_policy} " | awk '{print $2}'`
cgi_show_title "HTTP管控->策略组->添加策略"
tblexists=`${FLOWEYE} table list`

echo -n "
<br>
<form method=post onsubmit=\"return beforeAddRule(this)\" action=\"${myself}\">
<table width=600 border=0 cellspacing=0 cellpadding=3 bgcolor=\"#ffffff\">
<tr id=row1>
	<td width=40></td>
        <td width=120 align=left>策略组</td>
	<td width=130 align=left><b>${policyname}</b></td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>策略标识</td>
	<td align=left><input align=right type=text name=polno style=\"width:130\" value=\"${CGI_polno}\"></input>&nbsp;(1~65535)</td>
</tr>
</table>
<br>
<table style=\"width:600; border-bottom:1px #787882 solid; color:#000000\">
<tr><td align=left style=\"font-size:11px\"><b>匹配条件</b></td></tr>
</table>
<br>
<table width=600 border=0 cellspacing=0 cellpadding=3 bgcolor=\"#ffffff\">
<tr id=row1>
	<td width=40></td>
        <td width=120 align=left>源地址</td>
        <td width=130 align=left>
		<select name=intype style=\"width:100%\" value=\"any\" onchange=\"onIntypeChanged(this)\">
			<option value=\"any\" selected>任意地址</option>
			<option value=\"net\">xxx.xxx.xxx.xxx/nn</option>
			<option value=\"range\">n.n.n.n-m.m.m.m</option>
		";
			if [ "${tblexists}" != "" ]; then
				echo "<option value=\"table\">IP群组</option>"
			fi
		
echo -n "
		</select>
	</td>
	<td width=* align=left>
		<input type=text name=inipnet style=\"width:120px;display:none\"></input>
		<input type=text name=iniprng style=\"width:160px;display:none\"></input>
		<select name=iniptbl style=\"width:120px;display:none\">
		";
			${FLOWEYE} table list | while read tblid tblname
			do
				echo "<option value=\"${tblid}\">${tblname}</option>"
			done
		
echo -n "
		</select>
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>访问方法</td>
        <td><select name=method style=\"width:100%\">
		<option value=\"any\">任意</option>
		<option value=\"get\">GET</option>
		<option value=\"post\">POST</option>
	</select></td> 
	<td width=* align=left></td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>网站域名</td>
        <td><select name=dns style=\"width:100%\">
		<option value=0>任意域名</option>
	";
		${FLOWEYE} dns listgrp | while read type id name theothers
		do
			echo "<option value=${id}>${name}</option>"
		done
	
echo -n "
	</select></td> 
	<td></td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>文件类型</td>
        <td><select name=ext style=\"width:100%\">
		<option value=0>任意类型</option>
	";
		${FLOWEYE} urlfilter listext | while read id name theothers
		do
			echo "<option value=${id}>${name}</option>"
		done
	
echo -n "
	</select></td>
	<td></td>
</tr>
<tr id=row1>
        <td ></td>
        <td align=left>共享用户>=</td>
        <td><input type=text name=natip value=\"${CGI_natip}\" style=\"width:130\"></input></td>
        <td align=left><a style=\"color:#0000ff\" onmouseover=\"TagToTip('hlpnatip')\" onmouseout=\"UnTip()\">(个, 0~255, 0表示忽略)</a></td>
</tr>
<tr id=row1>
        <td></td>
        <td align=left>移动设备>=</td>
        <td><input type=text name=hasms value=\"${CGI_hasms}\" style=\"width:130\"></input></td>
        <td align=left><a style=\"color:#0000ff\">(个, 0~255, 0表示忽略)</a></td>
</tr>
<tr id=row1>
        <td></td>
        <td align=left>QQ用户数>=</td>
        <td><input type=text name=qqcnt value=\"${CGI_qqcnt}\" style=\"width:130\"></input></td>
        <td align=left><a style=\"color:#0000ff\">(个, 0~255, 0表示忽略)</a></td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>每个IP只匹配一次</td>
        <td><select type=text name=onlyfirst value=\"${CGI_onlyfirst}\" style=\"width:100%\">
	"; if [ ${CGI_onlyfirst} -eq 0 ]; then
		echo "<option value=0 selected>否</option>"
		echo "<option value=1>是</option>"
	    else
		echo "<option value=0>否</option>"
		echo "<option value=1 selected>是</option>"
	    fi
echo -n "</select</td>
	<td width=* align=left></td>
</tr>
</table>
<br>
<table style=\"width:600; border-bottom:1px #787882 solid; color:#000000\">
<tr><td align=left style=\"font-size:11px\"><b>执行动作</b></td></tr>
</table>
<br>
<table width=600 border=0 cellspacing=0 cellpadding=3 bgcolor=\"#ffffff\">
<tr id=row1>
	<td width=40></td>
        <td width=120 align=left>动作类型</td>
        <td width=* align=left>
		<select name=action style=\"width:130\" value=\"${CGI_action}\" onchange=\"onActionChanged(this)\">
			<option value=\"accept\" selected>允许</option>
			<option value=\"deny\">阻断</option>
			<option value=\"prompt\">信息提示</option>
			<option value=\"redirect\">URL跳转</option>
			<option value=\"reqfwd\">请求报文镜像</option>
		</select>
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>输出线路</td>
        <td align=left>
		<select name=outpxy style=\"width:130\" value=\"${CGI_outpxy}\">
		";
			if [ "${CGI_outpxy}" = "NULL" ]; then
				echo "<option value=\"NULL\" selected>原路返回</option>"
			else
				echo "<option value=\"NULL\">原路返回</option>"
			fi
			${FLOWEYE} nat listproxy type=proxy.pppoe | while read type pxyid pxyname theothers
			do
				if [ "${pxyname}" = "${CGI_outpxy}" ]; then
					echo "<option value=\"${pxyname}\" selected>${pxyname}</option>"
				else
					echo "<option value=\"${pxyname}\">${pxyname}</option>"
				fi
			done
		
echo -n "
		</select>
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left id=actargname>动作参数</td>
        <td><input type=text name=actarg value=\"${CGI_actarg}\" style=\"width:100%\"></input></td>
</tr>
</table>
<table style=\"width:600; border-bottom:1px #787882 solid; color:#0000ff\">
<tr><td align=right>&nbsp;</td></tr>
</table>
<table style=\"width:600\"> 
<tr>
        <td align=right>
		<input type=submit style=\"width:80\" value=\"提交\"></input>
		<input type=button style=\"width:80\" value=\"取消\" onclick=\"onCancel('${CGI_policy}')\"></input>
		<input type=hidden name=policy value=\"${CGI_policy}\"></input>
	</td>
</tr>
</table>
</form>
</body>
</html>
";