#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n "";
. ../common/common.sh 
myself="/cgi-bin/Setup/`basename $0`"

echo -n "
<script type=\"text/javascript\" src=\"/img/common.js\"></script>
<script language=\"javascript\">
function beforeAddTime(frm)
{
	var schid = document.getElementsByName(\"schid\")[0];
	schid.value = TrimAll(schid.value);
	if (!IsDigitIn(1, 65535)) {
		alert(\"编号必须介于1~65535之间!\");
		return false;
	}
	
	return true;
}
function onCancel()
{
	window.location.href = \"/cgi-bin/Setup/urlfilter_listime\";
}
function onMonthChanged(obj)
{
	var i;
	var sday = document.getElementsByName(\"startday\")[0];
	var eday = document.getElementsByName(\"endday\")[0];
	sday.options.length = 0;
	eday.options.length = 0;
	if (obj.value == \"0\") {
		for (i = 1; i <= 7; i++) {
			var opt1 = document.createElement(\"option\");
			var opt2 = document.createElement(\"option\");
			opt1.value = i;
			opt2.value = i;
			switch (i) {
			case 1:
				opt1.text = \"星期一\";
				opt2.text = \"星期一\";
				break;
			case 2:
				opt1.text = \"星期二\";
				opt2.text = \"星期二\";
				break;
			case 3:
				opt1.text = \"星期三\";
				opt2.text = \"星期三\";
				break;
			case 4:
				opt1.text = \"星期四\";
				opt2.text = \"星期四\";
				break;
			case 5:
				opt1.text = \"星期五\";
				opt2.text = \"星期五\";
				break;
			case 6:
				opt1.text = \"星期六\";
				opt2.text = \"星期六\";
				break;
			case 7:
				opt1.text = \"星期日\";
				opt2.text = \"星期日\";
				break;
			}
			sday.options.add(opt1);
			eday.options.add(opt2);
		}
		sday.selectedIndex = 0;
		eday.selectedIndex = 6;
	}
	else {
		var cnt = 31;
		if (obj.value == \"4\" || obj.value == \"6\" ||
		    obj.value == \"9\" || obj.value == \"11\"){ 
			cnt = 30;
		}
		else
		if (obj.value == \"2\") {
			cnt = 29;
		}
		
		for (i = 1; i <= cnt; i++) {
			opt1 = document.createElement(\"option\");
			opt1.value = i;
			opt1.text  = i;
			opt2 = document.createElement(\"option\");
			opt2.value = i;
			opt2.text  = i;
			sday.options.add(opt1);
			eday.options.add(opt2);
		}
		sday.selectedIndex = 0;
		eday.selectedIndex = cnt - 1;
	}
}
</script>
";
if [ "${REQUEST_METHOD}" = "POST" ]; then
	operator_check "${myself}"
	errmsg=`${FLOWEYE} urlfilter addtime id=${CGI_schid} month=${CGI_month} startday=${CGI_startday} \
endday=${CGI_endday} start=${CGI_starthour}:${CGI_startmin}:${CGI_startsec} \
end=${CGI_endhour}:${CGI_endmin}:${CGI_endsec} group=${CGI_policygrp} disable=${CGI_status} \
ipmin=${CGI_ipmin} ipmax=${CGI_ipmax}`
	if [ "$?" != "0" ]; then
		[ "${errmsg}" = "id exist" ] && errmsg="编号同现有时段重复"
		afm_dialog_msg "操作失败:${errmsg}"
	else
		afm_dialog_msg "操作成功!"
		afm_load_page 0 "/cgi-bin/Setup/urlfilter_listime"
		exit 0
	fi
fi

echo -n "
<body>
"; cgi_show_title "HTTP管控->策略调度->添加时段" 
echo -n "
<br>
<form method=post onsubmit=\"return beforeAddTime(this)\" action=\"${myself}\">
<table style=\"font:14px;table-layout:nowrap;\" width=600 border=0 cellspacing=0 cellpadding=3 bgcolor=\"#ffffff\">
<tr id=row1>
	<td width=40></td>
        <td width=100 align=left>时段编号</td>
	<td width=* align=left>
		<input type=text name=schid style=\"width:60\"></input>&nbsp;(1~128,小编号优先匹配)
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>是否有效</td>
        <td align=left>
	<select name=status style=\"width:60\">
		<option value=\"0\">有效</option>
		<option value=\"1\">无效</option>
	</select>
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>时段日期</td>
        <td align=left>
	<select name=month value=\"0\" style=\"width:60\" onchange=\"onMonthChanged(this)\">
		<option value=\"0\">每周</option>
		<option value=\"1\">1月</option>
		<option value=\"2\">2月</option>
		<option value=\"3\">3月</option>
		<option value=\"4\">4月</option>
		<option value=\"5\">5月</option>
		<option value=\"6\">6月</option>
		<option value=\"7\">7月</option>
		<option value=\"8\">8月</option>
		<option value=\"9\">9月</option>
		<option value=\"10\">10月</option>
		<option value=\"11\">11月</option>
		<option value=\"12\">12月</option>
        </select>
	<select name=startday value=\"1\" style=\"width:65\">
		<option value=\"1\">星期一</option>
		<option value=\"2\">星期二</option>
		<option value=\"3\">星期三</option>
		<option value=\"4\">星期四</option>
		<option value=\"5\">星期五</option>
		<option value=\"6\">星期六</option>
		<option value=\"7\">星期日</option>
	</select>至<select name=endday value=\"7\" style=\"width:65\">
		<option value=\"1\">星期一</option>
		<option value=\"2\">星期二</option>
		<option value=\"3\">星期三</option>
		<option value=\"4\">星期四</option>
		<option value=\"5\">星期五</option>
		<option value=\"6\">星期六</option>
		<option value=\"7\" selected>星期日</option>
	</select>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>开始时刻</td>
        <td align=left>
        <select name=starthour value=\"00\" style=\"width:56\">
                <option value=\"00\">0</option>
                <option value=\"01\">1</option>
                <option value=\"02\">2</option>
                <option value=\"03\">3</option>
                <option value=\"04\">4</option>
                <option value=\"05\">5</option>
                <option value=\"06\">6</option>
                <option value=\"07\">7</option>
                <option value=\"08\">8</option>
                <option value=\"09\">9</option>
                <option value=\"10\">10</option>
                <option value=\"11\">11</option>
                <option value=\"12\">12</option>
                <option value=\"13\">13</option>
                <option value=\"14\">14</option>
                <option value=\"15\">15</option>
                <option value=\"16\">16</option>
                <option value=\"17\">17</option>
                <option value=\"18\">18</option>
                <option value=\"19\">19</option>
                <option value=\"20\">20</option>
                <option value=\"21\">21</option>
                <option value=\"22\">22</option>
                <option value=\"23\">23</option>
        </select>时<select name=startmin value=0 style=\"width:56\">
                <option value=\"00\">0</option>
                <option value=\"01\">1</option>
                <option value=\"02\">2</option>
                <option value=\"03\">3</option>
                <option value=\"04\">4</option>
                <option value=\"05\">5</option>
                <option value=\"06\">6</option>
                <option value=\"07\">7</option>
                <option value=\"08\">8</option>
                <option value=\"09\">9</option>
                <option value=\"10\">10</option>
                <option value=\"11\">11</option>
                <option value=\"12\">12</option>
                <option value=\"13\">13</option>
                <option value=\"14\">14</option>
                <option value=\"15\">15</option>
                <option value=\"16\">16</option>
                <option value=\"17\">17</option>
                <option value=\"18\">18</option>
                <option value=\"19\">19</option>
                <option value=\"20\">20</option>
                <option value=\"21\">21</option>
                <option value=\"22\">22</option>
                <option value=\"23\">23</option>
                <option value=\"24\">24</option>
                <option value=\"25\">25</option>
                <option value=\"26\">26</option>
                <option value=\"27\">27</option>
                <option value=\"28\">28</option>
                <option value=\"29\">29</option>
                <option value=\"30\">30</option>
                <option value=\"31\">31</option>
                <option value=\"32\">32</option>
                <option value=\"33\">33</option>
                <option value=\"34\">34</option>
                <option value=\"35\">35</option>
                <option value=\"36\">36</option>
                <option value=\"37\">37</option>
                <option value=\"38\">38</option>
                <option value=\"39\">39</option>
                <option value=\"40\">40</option>
                <option value=\"41\">41</option>
                <option value=\"42\">42</option>
                <option value=\"43\">43</option>
                <option value=\"44\">44</option>
                <option value=\"45\">45</option>
                <option value=\"46\">46</option>
                <option value=\"47\">47</option>
                <option value=\"48\">48</option>
                <option value=\"49\">49</option>
                <option value=\"50\">50</option>
                <option value=\"51\">51</option>
                <option value=\"52\">52</option>
                <option value=\"53\">53</option>
                <option value=\"54\">54</option>
                <option value=\"55\">55</option>
                <option value=\"56\">56</option>
                <option value=\"57\">57</option>
                <option value=\"58\">58</option>
                <option value=\"59\">59</option>
        </select>分<select name=startsec value=0 style=\"width:56\">
                <option value=\"00\">0</option>
                <option value=\"01\">1</option>
                <option value=\"02\">2</option>
                <option value=\"03\">3</option>
                <option value=\"04\">4</option>
                <option value=\"05\">5</option>
                <option value=\"06\">6</option>
                <option value=\"07\">7</option>
                <option value=\"08\">8</option>
                <option value=\"09\">9</option>
                <option value=\"10\">10</option>
                <option value=\"11\">11</option>
                <option value=\"12\">12</option>
                <option value=\"12\">12</option>
                <option value=\"13\">13</option>
                <option value=\"14\">14</option>
                <option value=\"15\">15</option>
                <option value=\"16\">16</option>
                <option value=\"17\">17</option>
                <option value=\"18\">18</option>
                <option value=\"19\">19</option>
                <option value=\"20\">20</option>
                <option value=\"21\">21</option>
                <option value=\"22\">22</option>
                <option value=\"23\">23</option>
                <option value=\"24\">24</option>
                <option value=\"25\">25</option>
                <option value=\"26\">26</option>
                <option value=\"27\">27</option>
                <option value=\"28\">28</option>
                <option value=\"29\">29</option>
                <option value=\"30\">30</option>
                <option value=\"31\">31</option>
                <option value=\"32\">32</option>
                <option value=\"33\">33</option>
                <option value=\"34\">34</option>
                <option value=\"35\">35</option>
                <option value=\"36\">36</option>
                <option value=\"37\">37</option>
                <option value=\"38\">38</option>
                <option value=\"39\">39</option>
                <option value=\"40\">40</option>
                <option value=\"41\">41</option>
                <option value=\"42\">42</option>
                <option value=\"43\">43</option>
                <option value=\"44\">44</option>
                <option value=\"45\">45</option>
                <option value=\"46\">46</option>
                <option value=\"47\">47</option>
                <option value=\"48\">48</option>
                <option value=\"49\">49</option>
                <option value=\"50\">50</option>
                <option value=\"51\">51</option>
                <option value=\"52\">52</option>
                <option value=\"53\">53</option>
                <option value=\"54\">54</option>
                <option value=\"55\">55</option>
                <option value=\"56\">56</option>
                <option value=\"57\">57</option>
                <option value=\"58\">58</option>
                <option value=\"59\">59</option>
	</select>秒
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>结束时刻</td>
        <td align=left>
	<select name=endhour value=23 style=\"width:56\">
		<option value=\"00\">0</option>
		<option value=\"01\">1</option>
		<option value=\"02\">2</option>
		<option value=\"03\">3</option>
		<option value=\"04\">4</option>
		<option value=\"05\">5</option>
		<option value=\"06\">6</option>
		<option value=\"07\">7</option>
		<option value=\"08\">8</option>
		<option value=\"09\">9</option>
		<option value=\"10\">10</option>
		<option value=\"11\">11</option>
		<option value=\"12\">12</option>
		<option value=\"13\">13</option>
		<option value=\"14\">14</option>
		<option value=\"15\">15</option>
		<option value=\"16\">16</option>
		<option value=\"17\">17</option>
		<option value=\"18\">18</option>
		<option value=\"19\">19</option>
		<option value=\"20\">20</option>
		<option value=\"21\">21</option>
		<option value=\"22\">22</option>
		<option value=\"23\" selected>23</option>
	</select>时<select name=endmin value=59 style=\"width:56\">
		<option value=\"00\">0</option>
		<option value=\"01\">1</option>
		<option value=\"02\">2</option>
		<option value=\"03\">3</option>
		<option value=\"04\">4</option>
		<option value=\"05\">5</option>
		<option value=\"06\">6</option>
		<option value=\"07\">7</option>
		<option value=\"08\">8</option>
		<option value=\"09\">9</option>
		<option value=\"10\">10</option>
		<option value=\"11\">11</option>
		<option value=\"12\">12</option>
		<option value=\"13\">13</option>
		<option value=\"14\">14</option>
		<option value=\"15\">15</option>
		<option value=\"16\">16</option>
		<option value=\"17\">17</option>
		<option value=\"18\">18</option>
		<option value=\"19\">19</option>
		<option value=\"20\">20</option>
		<option value=\"21\">21</option>
		<option value=\"22\">22</option>
		<option value=\"23\">23</option>
		<option value=\"24\">24</option>
		<option value=\"25\">25</option>
		<option value=\"26\">26</option>
		<option value=\"27\">27</option>
		<option value=\"28\">28</option>
		<option value=\"29\">29</option>
		<option value=\"30\">30</option>
		<option value=\"31\">31</option>
		<option value=\"32\">32</option>
		<option value=\"33\">33</option>
		<option value=\"34\">34</option>
		<option value=\"35\">35</option>
		<option value=\"36\">36</option>
		<option value=\"37\">37</option>
		<option value=\"38\">38</option>
		<option value=\"39\">39</option>
		<option value=\"40\">40</option>
		<option value=\"41\">41</option>
		<option value=\"42\">42</option>
		<option value=\"43\">43</option>
		<option value=\"44\">44</option>
		<option value=\"45\">45</option>
		<option value=\"46\">46</option>
		<option value=\"47\">47</option>
		<option value=\"48\">48</option>
		<option value=\"49\">49</option>
		<option value=\"50\">50</option>
		<option value=\"51\">51</option>
		<option value=\"52\">52</option>
		<option value=\"53\">53</option>
		<option value=\"54\">54</option>
		<option value=\"55\">55</option>
		<option value=\"56\">56</option>
		<option value=\"57\">57</option>
		<option value=\"58\">58</option>
		<option value=\"59\" selected>59</option>
	</select>分<select name=endsec value=59 style=\"width:56\">
		<option value=\"00\">0</option>
		<option value=\"01\">1</option>
		<option value=\"02\">2</option>
		<option value=\"03\">3</option>
		<option value=\"04\">4</option>
		<option value=\"05\">5</option>
		<option value=\"06\">6</option>
		<option value=\"07\">7</option>
		<option value=\"08\">8</option>
		<option value=\"09\">9</option>
		<option value=\"10\">10</option>
		<option value=\"11\">11</option>
		<option value=\"12\">12</option>
		<option value=\"13\">13</option>
		<option value=\"14\">14</option>
		<option value=\"15\">15</option>
		<option value=\"16\">16</option>
		<option value=\"17\">17</option>
		<option value=\"18\">18</option>
		<option value=\"19\">19</option>
		<option value=\"20\">20</option>
		<option value=\"21\">21</option>
		<option value=\"22\">22</option>
		<option value=\"23\">23</option>
		<option value=\"24\">24</option>
		<option value=\"25\">25</option>
		<option value=\"26\">26</option>
		<option value=\"27\">27</option>
		<option value=\"28\">28</option>
		<option value=\"29\">29</option>
		<option value=\"30\">30</option>
		<option value=\"31\">31</option>
		<option value=\"32\">32</option>
		<option value=\"33\">33</option>
		<option value=\"34\">34</option>
		<option value=\"35\">35</option>
		<option value=\"36\">36</option>
		<option value=\"37\">37</option>
		<option value=\"38\">38</option>
		<option value=\"39\">39</option>
		<option value=\"40\">40</option>
		<option value=\"41\">41</option>
		<option value=\"42\">42</option>
		<option value=\"43\">43</option>
		<option value=\"44\">44</option>
		<option value=\"45\">45</option>
		<option value=\"46\">46</option>
		<option value=\"47\">47</option>
		<option value=\"48\">48</option>
		<option value=\"49\">49</option>
		<option value=\"50\">50</option>
		<option value=\"51\">51</option>
		<option value=\"52\">52</option>
		<option value=\"53\">53</option>
		<option value=\"54\">54</option>
		<option value=\"55\">55</option>
		<option value=\"56\">56</option>
		<option value=\"57\">57</option>
		<option value=\"58\">58</option>
		<option value=\"59\" selected>59</option>
	</select>秒
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>在线用户</td>
        <td align=left><input type=text name=ipmin style=\"width:56px\" value=\"0\"></input>至<input type=text name=ipmax style=\"width:56px\" value=\"0\"></input>
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>策略组</td>
        <td align=left>
	<select name=policygrp style=\"width:208\">
	";
		${FLOWEYE} urlfilter listgrp | while read pid name
		do
			echo "<option value=\"${pid}\">${name}</option>"
		done
		echo "<option value=\"0\">空策略组</option>"
	
echo -n "
	</select>
	</td>
</tr>
</table>
<table style=\"width:600; border-bottom:1px #787882 solid; color:#0000ff\">
<tr><td align=right>&nbsp;</td></tr>
</table>
<table style=\"width:600\"> 
<tr>
        <td align=right>
		<input type=submit style=\"width:80\" value=\"提交\"></input>
		<input type=button style=\"width:80\" value=\"取消\" onclick=\"onCancel()\"></input>
	</td>
</tr>
</table>
</form>
</body>
</html>
";