#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n "";
. ../common/common.sh 
myself="/cgi-bin/Setup/`basename $0`"
[ "${CGI_group}" = "-1" ] && CGI_group=0

echo -n "
<script type=\"text/javascript\" src=\"/img/common.js\"></script>
<script language=\"javascript\">
function beforeCommit(frm)
{
	var usrname = document.getElementsByName(\"usrname\")[0];
	var passwd1 = document.getElementsByName(\"passwd1\")[0];
	var passwd2 = document.getElementsByName(\"passwd2\")[0];
	var maxlogin = document.getElementsByName(\"maxlogin\")[0];
	var ipaddr = document.getElementsByName(\"ipaddr\")[0];
	usrname.value = TrimAll(usrname.value);
	if (usrname.value == \"\") {
		alert(\"请输入账号名称!\");
		usrname.select();
		return false;
	}
	passwd1.value = TrimAll(passwd1.value);
	if (passwd1.value == \"\") {
		alert(\"请输入密码!\");
		passwd1.select();
		return false;
	}
	if (passwd2.value != passwd1.value) {
		alert(\"两次输入密码不同，请重新输入!\");
		passwd1.select();
		return false;
	}
	maxlogin.value = TrimAll(maxlogin.value);
	if (maxlogin.value == \"\") {
		alert(\"请输入最大在线人数!\");
		maxlogin.select();
		return false;
	}
	ipaddr.value = TrimAll(ipaddr.value);
	if (ipaddr.value != \"\" && !IsIPAddr(ipaddr.value)) {
		alert(\"请输入正确的IP地址!\");
		ipaddr.select();
		return false;
	}
	return true;
}
function onCancel() 
{
	window.location.href = \"/cgi-bin/Setup/usrinfo_list?group=${CGI_group}\";
}
</script>
";
if [ "${REQUEST_METHOD}" = "POST" ]; then
	operator_check "${myself}"
	args="group=${CGI_group} name=${CGI_usrname} passwd=${CGI_passwd1}"
	args="${args} enable=${CGI_enable} maxlogin=${CGI_maxlogin}"
	[ "${CGI_ipaddr}" != "" ] && args="${args} ipaddr=${CGI_ipaddr}"
	errmsg=`${FLOWEYE} usrinfo add ${args}`
	if [ "$?" != "0" ]; then
		afm_dialog_msg "操作失败:${errmsg}"
	else
		afm_load_page 0 "/cgi-bin/Setup/usrinfo_list?group=${CGI_group}"
		exit 0
	fi
fi

echo -n "
<body>
"; cgi_show_title "Web认证->账号管理->添加账号" 
echo -n "
<br>
<form method=post onsubmit=\"return beforeCommit(this)\" action=\"${myself}\">
<table style=\"font:14px\" width=600 border=0 cellspacing=0 cellpadding=3 bgcolor=\"#ffffff\">
<tr id=row1>
	<td width=40></td>
	<td width=80 align=left>用户组</td>
	<td width=120 align=left>
		<select style=\"width:120\" name=group value=\"${CGI_group}\">
		";
			${FLOWEYE} usrinfo listgrp | while read grpid grpname theothers
			do
				if [ "${grpid}" = "${CGI_group}" -o "${grpname}" = "${CGI_group}" ]; then
					echo "<option value=\"${grpid}\" selected>${grpname}</option>"
				else
					echo "<option value=\"${grpid}\">${grpname}</option>"
				fi
			done
		
echo -n "</select>
	</td>
</tr>
<tr id=row1>
	<td width=40></td>
        <td width=80 align=left>账号名称</td>
	<td width=400 align=left>
		<input type=text name=usrname style=\"width:120px\" value=\"${CGI_usrname}\"></input>
		&nbsp;&nbsp;(不超过20个英文字符或10个中文字符)
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>状态</td>
        <td align=left>
		<select name=enable style=\"width:120px\" value=1>
		<option value=1 selected>允许使用</option>
		<option value=0>禁止使用</option>
		</select>
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>最大在线</td>
        <td align=left><input type=text class=text name=maxlogin style=\"width:120px\" value=\"1\"></input>
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>绑定IP</td>
        <td align=left><input type=text class=text name=ipaddr style=\"width:120px\" value=\"${CGI_ipaddr}\"></input>
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>密码</td>
        <td align=left>
		<input type=password class=text name=passwd1 style=\"width:120px\" value=\"${CGI_passwd1}\"></input>
		&nbsp;&nbsp;(不超过21个英文字符,不能含冒号)
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>再输入密码</td>
        <td align=left>
		<input type=password class=text name=passwd2 style=\"width:120px\" value=\"${CGI_passwd1}\"></input>
		&nbsp;&nbsp;(不超过21个英文字符,不能含冒号)
	</td>
</tr>
</table>
<table style=\"width:600; border-bottom:1px #787882 solid; color:#0000ff\">
<tr><td align=right>&nbsp;</td></tr>
</table>
<table style=\"width:600\"> 
<tr>
        <td align=right>
		<input type=submit style=\"width:80\" value=\"提交\"></input>
		<input type=button style=\"width:80\" value=\"取消\" onclick=\"onCancel()\"></input>
	</td>
</tr>
</table>
</form>
</body>
</html>
";