#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n ""; 
. ../common/common.sh
myself="/cgi-bin/Setup/`basename $0`"

echo -n "
<script languate=\"javascript\">
function Validate(frm)
{
	var dbfile = document.getElementsByName(\"cfgfile\")[0];
	if (dbfile.value == \"\") {
		alert(\"请输入配置文件路径!\");
		return false;
	}
	if (confirm(\"确定要上传配置文件?\"))
		return true;
	else
		return false;
}
</script>
";
if [ "${REQUEST_METHOD}" = "POST" ]; then
	operator_check "${myself}"
	errmsg=`${FLOWEYE} usrinfo load path=${CGI_cfgfile}`
	if [ "$?" != "0" ]; then
		afm_dialog_msg "出错:${errmsg}"
	else
		afm_dialog_msg "成功导入文件!"
	fi
	rm -f ${CGI_cfgfile}
	sync
fi

echo -n "
<body>
"; 
cgi_show_title "其它对象->IP标识->从文件导入"

echo -n "
<br>
<table width=700 border=0 cellspacing=1 cellpadding=1 bgcolor=\"#ffffff\">
<form method=post onsubmit=\"return Validate(this)\" action=\"${myself}\" enctype=\"multipart/form-data\">
<tr height=22>
	<td width=20></td>
	<td width=160 style=\"font:13px bold\" align=left>请输入配置文件路径:</td>
	<td width=* class=cssTDArial align=left>
		<input type=file name=cfgfile style=\"width:430px\">
	</td>
	<td align=right>
		<input type=submit style=\"width:90\" value=\"导入文件\"></input>
	</td>
</tr>
</form>
</table>
</body>
</html>
";