#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n ""; . ../common/common.sh 
myself="/cgi-bin/Setup/`basename $0`"

echo -n "
<script type=\"text/javascript\" src=\"/img/common.js\"></script>
<script language=\"javascript\">
function beforeAddGroup(frm)
{
	var grp;
	grp = document.getElementsByName(\"grpname\")[0];
	grp.value = TrimAll(grp.value);
	if (!IsName(grp.value)) {
		alert(\"名称中不能包含&等特殊字符!\");
		grp.select();
		return false;
	}
	return true;
}
</script>
";
if [ "${REQUEST_METHOD}" = "POST" ]; then
	operator_check "/cgi-bin/Setup/usrinfo_list?ipgrp=${ipgrp}"
	errmsg=`${FLOWEYE} usrinfo addgrp name=${CGI_grpname}`
	if [ "$?" != "0" ]; then
		afm_dialog_msg "操作失败:${errmsg}"
	else
		ipgrp=`${FLOWEYE} usrinfo listgrp | grep " ${CGI_grpname}" | awk '{print $1}'`
		afm_load_page 0 "/cgi-bin/Setup/usrinfo_list?group=${ipgrp}"
		exit 0
	fi
fi

echo -n "
<body> 
"; cgi_show_title "Web认证->账号管理->添加组" 
echo -n "
<br>
";
if [ "${CGI_ipgrp}" != "" ]; then
	CGI_grpname=`${FLOWEYE} usrinfo listgrp | grep "^${CGI_ipgrp} " | awk '{print $2}'`
fi

echo -n "
	
<table width=\"76%\" border=0 cellspacing=0 cellpadding=3 bgcolor=\"#ffffff\">
<form method=post onsubmit=\"return beforeAddGroup(this)\" action=\"${myself}\">
<tr id=row1>
	<td width=40></td>
	<td width=120 align=left>请输入组名称</td>
	<td width=200 align=left>
		<input type=text class=text name=grpname value=\"${CGI_grpname}\" style=\"width:100%\" size=32></input>
		<input type=hidden name=ipgrp value=\"${CGI_ipgrp}\"></input>
	</td>
	"; if [ "${CGI_ipgrp}" = "" ]; then 
echo -n "
	<td align=right width=120px><input type=submit style=\"width:100\" value=\"创建组\"></input>
	"; else 
echo -n "
	<td align=right width=120px><input type=submit style=\"width:100\" value=\"修改名称\"></input>
	"; fi 
echo -n "
	<td width=*></td>
</tr>
</table>
</form>
</table>
</center>
</body>
</html>
";