#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n "";
. ../common/common.sh 
myself="/cgi-bin/Pppoe/`basename $0`"
if [ "${CGI_where}" = "pool" ]; then
	returl="/cgi-bin/Pppoe/ippool_list"
else
	returl="/cgi-bin/Pppoe/pppoe_extacct"
fi

echo -n "
<link rel=\"stylesheet\" type=\"text/css\" href=\"/img/cal.css\" />
<script type=\"text/javascript\" src=\"/img/common.js\"></script>
<script type=\"text/javascript\" src=\"/img/jq.js\"></script>
<script type=\"text/javascript\" src=\"/img/cal.js\"></script>
<script language=\"javascript\">
function beforeCommit(frm)
{
	var account = document.getElementsByName(\"account\")[0];
	var expire  = document.getElementsByName(\"expire\")[0];
	account.value = TrimAll(account.value);
	if (account.value == \"\") {
		alert(\"请输入账号名称!\");
		account.select();
		return false;
	}
	if (!IsName(account.value)) {
		alert(\"名称中不能有&等特殊字符!\");
		account.select();
		return false;
	}
	expire.value = TrimAll(expire.value);
	if (expire.value == \"\") {
		alert(\"请输入有效期\");
		expire.select();
		return false;
	}
	var outif = document.getElementsByName(\"outif\")[0];
	if (outif.value == \"\") {
		alert(\"请输入网络出口!\");
		outif.select();
		return false;
	}
	var outvlan = document.getElementsByName(\"outvlan\")[0];
	outvlan.value = TrimAll(outvlan.value);
	
	var cname  = document.getElementsByName(\"cname\")[0];
	var phone  = document.getElementsByName(\"phone\")[0];
	var card   = document.getElementsByName(\"card\")[0];
	var other  = document.getElementsByName(\"other\")[0];
	cname.value = TrimAll(cname.value);
	card.value  = TrimAll(card.value);
	phone.value = TrimAll(phone.value);
	other.value = TrimAll(other.value);
	
	return true;
}
function onCancel() 
{
	window.location.href = \"${returl}\";
}
String.prototype.trim = function () {
    var $ = /^\s+|\s+$/g;
    return function () {
        return this.replace($, \"\")
    }
}();
jQuery(document).ready(function () {
	\$('#expire').Cal({enddate:2100});
	\$('#start').Cal({enddate:2100});
	Date.prototype.Format = function(format){
		var o = {
		\"M+\" : this.getMonth()+1, //month
		\"d+\" : this.getDate(),    //day
		\"h+\" : this.getHours(),   //hour
		\"m+\" : this.getMinutes(), //minute
		\"s+\" : this.getSeconds(), //second
		\"q+\" : Math.floor((this.getMonth()+3)/3),  //quarter
		\"S\" : this.getMilliseconds() //millisecond
		};
		if(/(y+)/.test(format)){
			format=format.replace(RegExp.\$1,(this.getFullYear()+\"\").substr(4 - RegExp.\$1.length));
		}
		for(var k in o){
			if(new RegExp(\"(\"+ k +\")\").test(format)){
				format = format.replace(RegExp.\$1,RegExp.\$1.length==1 ? o[k] :(\"00\"+ o[k]).substr((\"\"+ o[k]).length));
			}
		}
		return format;
	};
	\$('#link_add_month').bind({
		'mouseover':function(e){
			\$('#box_choose_month').show();
		},
		'mouseout':function(e){
			\$('#box_choose_month').hide();
		}
	});
	
	\$('span',\$('#box_choose_month')).bind({
		'click':function(e){
			var ctl = \$('#expire'),
			d1 = ctl.val();
			if(d1 == '') return;
			
			var addm = parseInt(\$(this).attr('m')),d2=0,nowTime = (new Date()).Format('yyyy-MM-dd');
			d1 = d1.trim();
			if(/^\d{4}-\d{1,2}-\d{1,2}(\s+\d{2}:\d{1,2})?\$/.test(d1)){
				if(/1970-01-01/.test(d1)){
					d1 = nowTime;
				}
			}else{
				d1 = nowTime;
			}
			
			var t,pos,y,m,om,d,od,pd,pt,md = [31,28,31,30,31,30,31,31,30,31,30,31];
			if((pos = d1.indexOf(' ')) !== -1){
				pt = d1.substr(pos+1);
				pd = d1.substr(0,pos);
			}else{
				pt = '23:59';
				pd = d1;
			}
			pd = pd.split('-');
			
			y = parseInt(pd[0],10);
			om = m = parseInt(pd[1],10);
			od = d = parseInt(pd[2],10);
				
			if(addm + m > 12){
				y++;
				m = addm+m-12;
			}else{
				m = m + addm;
			}
			
			if(y % 4 == 0)md[1] = 29;
			if(md[om-1] == od){
				d = md[m-1];
			}
			m = '0' + m;
			d = '0' + d;
			d2 = y+'-'+m.substr(m.length-2)+'-'+d.substr(d.length-2);
			
			ctl.val(d2);
		}
	});
});
</script>
";
if [ "${REQUEST_METHOD}" = "POST" ]; then 
	operator_check "${myself}" pppoeman
	if [ "${CGI_outif}" != "" ]; then
		cmdargs="poolid=${CGI_poolid} name=${CGI_account} maxonline=1 password=_123456_ start=${CGI_start} expire=${CGI_expire}" 
		cmdargs="${cmdargs} outif=${CGI_outif}"
		[ "${CGI_outvlan}" != "" ] && cmdargs="${cmdargs} outvlan=${CGI_outvlan}"
		[ "${CGI_cname}" != "" ] && cmdargs="${cmdargs} cname=${CGI_cname}"
		[ "${CGI_phone}" != "" ] && cmdargs="${cmdargs} phone=${CGI_phone}"
		[ "${CGI_card}"  != "" ] && cmdargs="${cmdargs} card=${CGI_card}"
		[ "${CGI_other}" != "" ] && cmdargs="${cmdargs} other=${CGI_other}"
		errmsg=`${FLOWEYE} pppoeacct add ${cmdargs}`
		if [ "$?" != "0" ]; then
			[ "${errmsg}" = "EXIST" ] && errmsg="账号存在!"
			afm_dialog_msg "操作失败:${errmsg}"
		else
			afm_load_page 0 "/cgi-bin/Pppoe/pppoe_extacct"
			exit 0
		fi
	else
		afm_dialog_msg "请输入网络出口!"
	fi
fi
[ "${CGI_expire}" = "" ] && CGI_expire=`date +%Y-%m-%d`
[ "${CGI_start}" = "" ] && CGI_start=`date +%Y-%m-%d`

echo -n "
<body>
"; cgi_show_title "PPPOE认证->代理账号->添加账号" 
echo -n "
<br>
<form method=post onsubmit=\"return beforeCommit(this)\" action=\"${myself}\">
<table style=\"font:14px\" width=700 border=0 cellspacing=0 cellpadding=3 bgcolor=\"#ffffff\">
<tr id=row1>
	<td></td>
        <td align=left>服务组</td>
        <td align=left>
		<select name=poolid value=\"${CGI_poolid}\" style=\"width:150;height:21\">
";
		${FLOWEYE} pppoeippool list | while read gid name theothers
		do
			[ "${name}" = "NULL" ] && name="${gid}"
			if [ "${gid}" = "${CGI_poolid}" ]; then
				echo "<option value=${gid} selected>${name}</option>"
			else
				echo "<option value=${gid}>${name}</option>"
			fi
		done
	

echo -n "
		</select>
	</td>
</tr>
<tr id=row1>
	<td width=40></td>
        <td width=80 align=left>账号名称</td>
	<td width=* align=left>
		<input type=text name=account style=\"width:150px\" value=\"${CGI_account}\"></input>
		&nbsp;(不超过30个英文字符或15个中文字符)
	</td>
</tr>
<tr id=row1>
	<td width=40></td>
        <td width=80 align=left>网络出口</td>
	<td width=* align=left>
		<select name=outif style=\"width:150px\" value=\"${CGI_outif}\">
		";
			${FLOWEYE} if list | while read ifname ifmode ifzone theothers
			do
				[ "${ifzone}" = "inside" ] && continue
				if [ "${CGI_outif}" = "${ifname}" ]; then
					echo "<option value=${ifname} selected>${ifname}</option>"
				else
					echo "<option value=${ifname}>${ifname}</option>"
				fi
			done
		
echo -n "
		</select>&nbsp;(数据包经由此接口转发给外部运营商)
	</td>
</tr>
<tr id=row1>
	<td width=40></td>
        <td width=80 align=left>外出VLAN</td>
	<td width=* align=left><input type=text name=outvlan style=\"width:150px\" value=\"${CGI_outvlan}\"></input>&nbsp;(外出数据包的VLAN)</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>开通日期</td>
        <td align=left>
		<input type=\"text\" size=\"6\" name=\"start\" id=\"start\" validate=\"Date\" filter=\"filterDate\" setfn=\"setfnDate\" style=\"width:150px\" value=\"${CGI_start}\"/>
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>最后有效期</td>
        <td align=left>
		<input type=\"text\" size=\"6\" name=\"expire\" id=\"expire\" validate=\"Date\" filter=\"filterDate\" setfn=\"setfnDate\" style=\"width:150px\" value=\"${CGI_expire}\"/>
                <span id=\"link_add_month\"> +加时间
                    <div id=\"box_choose_month\">
                        <span m=\"1\">加1个月</span>
                        <span m=\"3\">加3个月</span>
                        <span m=\"6\">加半年</span>
                        <span m=\"12\">加1年</span> 
                    </div>
                </span>
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>姓名</td>
        <td align=left><input type=text class=text name=cname style=\"width:150px\" value=\"${CGI_cname}\"></input>&nbsp;(不超过7个字符)
</tr>
<tr id=row1>
	<td></td>
        <td align=left>身份证</td>
        <td align=left><input type=text class=text name=card style=\"width:150px\" value=\"${CGI_card}\"></input>&nbsp;(不超过18个字符)
</tr>
<tr id=row1>
	<td></td>
        <td align=left>联系电话</td>
        <td align=left><input type=text class=text name=phone style=\"width:150px\" value=\"${CGI_phone}\"></input>&nbsp;(不超过12个字符)
</tr>
<tr id=row1>
	<td></td>
        <td align=left>其他信息</td>
        <td align=left><input type=text class=text name=other style=\"width:450\" value=\"${CGI_other}\"></input>&nbsp;(不超过50个字符)
</tr>
</table>
<table style=\"width:700; border-bottom:1px #787882 solid; color:#0000ff\">
<tr><td align=right>&nbsp;</td></tr>
</table>
<table style=\"width:700\"> 
<tr>
        <td align=right>
		<input type=hidden name=where value=\"${CGI_where}\" />
		<input type=submit style=\"width:80\" value=\"提交\" />
		<input type=button style=\"width:80\" value=\"取消\" onclick=\"onCancel()\" />
	</td>
</tr>
</table>
</form>
</body>
</html>
";