#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n "";
. ../common/common.sh 
myself="/cgi-bin/Route/`basename $0`"

echo -n "
<script type=\"text/javascript\" src=\"/img/common.js\"></script>
<script language=\"javascript\">
	function beforeAdd(frm)
	{
		var mac  = document.getElementsByName(\"mac\")[0];
		var ip   = document.getElementsByName(\"ip\")[0];
		var desc = document.getElementsByName(\"desc\")[0];
		mac.value  = TrimAll(mac.value);
		ip.value   = TrimAll(ip.value);
		desc.value = TrimAll(desc.value);
		var adds = mac.value.split(\":\");
		if (adds.length != 6) {
			var adds2 = mac.value.split(\"-\");
			if (adds2.length != 6) {
				alert(\"请输入正确的MAC地址!\");
				return false;
			}
		}
		if (!IsIPAddr(ip.value)) {
			alert(\"请输入正确的IP地址!\");
			ip.select();
			return false;
		}
		if (mac.value == \"00:00:00:00:00:00\" ||
		    mac.value == \"00-00-00-00-00-00\") {
			alert(\"请输入有效MAC地址!\");
			mac.select();
			return false;
		}
		if (desc.value != \"\" && ! IsName(desc.value)) {
			alert(\"请输入有效的备注信息!\");
			desc.select();
			return false;
		}
		return true;
	}
	function onCancel() {
		window.location.href = \"/cgi-bin/Route/dhcpsvr_static\";
	}
</script>
";
if [ "${REQUEST_METHOD}" = "POST" ]; then
	operator_check "${myself}"
	cmdargs="mac=${CGI_mac} ip=${CGI_ip}"
	[ "${CGI_desc}" != "" ] && cmdargs="${cmdargs} desc=${CGI_desc}"
	errmsg=`${FLOWEYE} dhcpsta add ${cmdargs}`
	if [ "$?" != "0" ]; then
		afm_dialog_msg "操作失败:${errmsg}"
	else
		afm_load_page 0 "/cgi-bin/Route/dhcpsvr_static"
		exit 0
	fi
fi

echo -n "
<body>
"; cgi_show_title "DHCP服务->静态分配" 
echo -n "
<br>
<form method=post onsubmit=\"return beforeAdd(this)\" action=\"${myself}\">
<table style=\"font:14px\" width=600 border=0 cellspacing=0 cellpadding=3 bgcolor=\"#ffffff\">
<tr id=row1>
	<td width=\"40\"></td>
        <td width=\"80\" align=left>MAC地址</td>
        <td width=\"400\" align=left>
		<input type=text name=\"mac\" style=\"width:150px\" maxlength=\"17\" value=\"${CGI_mac}\" />
		&nbsp;(xx-xx-xx-xx-xx-xx 或 xx:xx:xx:xx:xx:xx)
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>静态IP</td>
	<td align=left><input type=text name=ip style=\"width:150px\" maxlength=\"15\" value=\"${CGI_ip}\" /></td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>备注</td>
	<td align=left>
		<input type=text name=desc style=\"width:150px\" maxlength=\"32\" value=\"${CGI_desc}\" />
		&nbsp;(可选)
	</td>
</tr>
</table>
<table style=\"width:600; border-bottom:1px #787882 solid; color:#0000ff\">
	<tr><td align=right>&nbsp;</td></tr>
</table>
<table style=\"width:600\"> 
<tr>
        <td align=right>
		<input type=submit style=\"width:80\" value=\"提交\"/>
		<input type=button style=\"width:80\" value=\"取消\" onclick=\"onCancel()\"/>
	</td>
</tr>
</table>
</form>
</body>
</html>
";