#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n "";
. ../common/common.sh 
myself="/cgi-bin/Route/`basename $0`"
if [ "${CGI_from}" != "" ]; then
        returnurl="${CGI_from}"
else
        returnurl="policy_list"
fi

echo -n "
<script type=\"text/javascript\" src=\"/img/common.js\"></script>
<script language=\"javascript\">
function beforeAddRule(frm)
{
	var rngs;
	var polno   = document.getElementsByName(\"polno\")[0];
	var srctype  = document.getElementsByName(\"srctype\")[0];
	var dsttype = document.getElementsByName(\"dsttype\")[0];
	var srcipnet = document.getElementsByName(\"srcipnet\")[0];
	var srciprng = document.getElementsByName(\"srciprng\")[0];
	var dstipnet= document.getElementsByName(\"dstipnet\")[0];
	var dstiprng= document.getElementsByName(\"dstiprng\")[0];
	var srcport  = document.getElementsByName(\"srcport\")[0];
	var dstport = document.getElementsByName(\"dstport\")[0];
	var apid    = document.getElementsByName(\"appid\")[0];
	var dscp    = document.getElementsByName(\"dscp\")[0];
	var nexthop = document.getElementsByName(\"nat_nexthop\")[0];
	var vlan    = document.getElementsByName(\"vlan\")[0];
	var ttl     = document.getElementsByName(\"ttl\")[0];
	var desc    = document.getElementsByName(\"desc\")[0];
	polno.value = TrimAll(polno.value);
	if (!IsDigitIn(polno.value, 1, 65535)) {
		alert(\"规则序号必须是介于1和65535之间的一个整数!\");
		polno.select();
		return false;
	}
	vlan.value = TrimAll(vlan.value);
	srcipnet.value = TrimAll(srcipnet.value);
	srciprng.value = TrimAll(srciprng.value);
	if (srctype.value == \"net\") {
		if (!IsIPAddr(srcipnet.value)) {
			alert(\"请输入正确的IP地址，格式为x.x.x.x/n\");
			srcipnet.select();
			return false;
		}
	}
	else
	if (srctype.value == \"range\") {
		rngs = srciprng.value.split(\"-\");
		if (rngs.length != 2 || !IsIPAddr(rngs[0]) || !IsIPAddr(rngs[1])) {
			alert(\"请输入正确的IP段，格式为x.x.x.x-y.y.y.y\");
			srciprng.select();
			return false;
		}
	}
	srcport.value = TrimAll(srcport.value);
	if (srcport.value == \"\") srcport.value = \"0\";
	rngs = srcport.value.split(\"-\");
	if (rngs.length == 2) {
		if (!IsDigitIn(rngs[0], 0, 65535) || !IsDigitIn(rngs[1], 0, 65535)) {
			alert(\"内网端口输入错误!\");
			srcport.select();
			return false;
		}
	}
	else {
		if (!IsDigitIn(srcport.value, 0, 65535)) {
			alert(\"内网端口输入错误!\");
			srcport.select();
			return false;
		}
	}
	dstipnet.value = TrimAll(dstipnet.value);
	dstiprng.value = TrimAll(dstiprng.value);
	if (dsttype.value == \"net\") {
		if (!IsIPAddr(dstipnet.value)) {
			alert(\"请输入正确的IP地址，格式为x.x.x.x/n\");
			dstipnet.select();
			return false;
		}
	}
	else
	if (dsttype.value == \"range\") {
		rngs = dstiprng.value.split(\"-\");
		if (rngs.length != 2 || !IsIPAddr(rngs[0]) || !IsIPAddr(rngs[1])) {
			alert(\"请输入正确的IP段，格式为x.x.x.x-y.y.y.y\");
			dstiprng.select();
			return false;
		}
	}
	dstport.value = TrimAll(dstport.value);
	if (dstport.value == \"\") dstport.value = \"0\";
	rngs = dstport.value.split(\"-\");
	if (rngs.length == 2) {
		if (!IsDigitIn(rngs[0], 0, 65535) || !IsDigitIn(rngs[1], 0, 65535)) {
			alert(\"外网端口输入错误!\");
			dstport.select();
			return false;
		}
	}
	else {
		if (!IsDigitIn(dstport.value, 0, 65535)) {
			alert(\"外网端口输入错误!\");
			dstport.select();
			return false;
		}
	}
		
	dscp.value = TrimAll(dscp.value);
	if (dscp.value == \"\") dscp.value = \"0\";
	if (!IsDigitIn(dscp.value, 0, 63)) {
		alert(\"请输入0~63!\");
		dscp.select();
		return false;
	}
	if (nexthop.value == \"\") {
		alert(\"请选择下一跳线路!\");
		nexthop.select();
		return false;
	}
	ttl.value = TrimAll(ttl.value);
	desc.value = TrimAll(desc.value);
	
	return true;
}
function onCancel()
{
	window.location.href = \"/cgi-bin/Route/${returnurl}\";
}
function onSrctypeChanged(obj) 
{
	var net = document.getElementsByName(\"srcipnet\")[0];
	var rng = document.getElementsByName(\"srciprng\")[0];
	var tbl = document.getElementsByName(\"srciptbl\")[0];
	if (obj.value == \"any\") {
		net.style.display = \"none\";
		rng.style.display = \"none\";
		tbl.style.display = \"none\";
	}
	else
	if (obj.value == \"net\") {
		net.style.display = \"block\";
		rng.style.display = \"none\";
		tbl.style.display = \"none\";
	}
	else
	if (obj.value == \"range\") {
		net.style.display = \"none\";
		rng.style.display = \"block\";
		tbl.style.display = \"none\";
	}
	else
	if (obj.value == \"table\") {
		net.style.display = \"none\";
		rng.style.display = \"none\";
		tbl.style.display = \"block\";
	}
}
function onDsttypeChanged(obj) 
{
	var net = document.getElementsByName(\"dstipnet\")[0];
	var rng = document.getElementsByName(\"dstiprng\")[0];
	var tbl = document.getElementsByName(\"dstiptbl\")[0];
	if (obj.value == \"any\") {
		net.style.display = \"none\";
		rng.style.display = \"none\";
		tbl.style.display = \"none\";
	}
	else
	if (obj.value == \"net\") {
		net.style.display = \"block\";
		rng.style.display = \"none\";
		tbl.style.display = \"none\";
	}
	else
	if (obj.value == \"range\") {
		net.style.display = \"none\";
		rng.style.display = \"block\";
		tbl.style.display = \"none\";
	}
	else
	if (obj.value == \"table\") {
		net.style.display = \"none\";
		rng.style.display = \"none\";
		tbl.style.display = \"block\";
	}
}
function onActionChanged(obj)
{
	var nattbl = document.getElementById(\"idNAT\");
	var routetbl = document.getElementById(\"idROUTE\");
	if (obj.value == \"nat\") {
		nattbl.style.display = \"block\";
		routetbl.style.display = \"none\";
	}
	else {
		nattbl.style.display = \"none\";
		routetbl.style.display = \"block\";
	}
}
function selectApp(appid)
{
	var url = \"/cgi-bin/Setup/app_select\";
	var retval = ShowDialog(url, \"\", 400, 600);
	if (retval == \"NONE\") return;
	var ar = retval.split(\",\");
	if (ar.length != 2) {
		alert(\"无效的返回值\");
		return;
	}
	var appid = document.getElementsByName(\"appid\")[0];
	var appname = document.getElementsByName(\"appname\")[0];
	appid.value = ar[0];
	appname.value = ar[1];
}
function onLoad()
{
	var action = document.getElementsByName(\"action\")[0];
	onActionChanged(action);
}
</script>
";
if [ "${REQUEST_METHOD}" = "POST" ]; then
	operator_check "/cgi-bin/Route/policy_list"
	cmdargs="id=${CGI_polno}"
	[ "${CGI_inifname}" != "any" ] && cmdargs="${cmdargs} inif=${CGI_inifname}"
	case "${CGI_srctype}" in
	"any")
		CGI_srcip="any"
		;;
	"net")
		CGI_srcip="${CGI_srcipnet}"
		;;
	"range")
		CGI_srcip="${CGI_srciprng}"
		;;
	"table")
		CGI_srcip="${CGI_srciptbl}"
		;;
	esac
	if [ "${CGI_srcport}" != "" -a "${CGI_srcport}" != "0" ]; then
		CGI_srcip="${CGI_srcip}:${CGI_srcport}"
	fi
	cmdargs="${cmdargs} src=${CGI_srcip}"
	case "${CGI_dsttype}" in
	"any")
		CGI_dstip="any"
		;;
	"net")
		CGI_dstip="${CGI_dstipnet}"
		;;
	"range")
		CGI_dstip="${CGI_dstiprng}"
		;;
	"table")
		CGI_dstip="${CGI_dstiptbl}"
		;;
	esac
	if [ "${CGI_dstport}" != "" -a "${CGI_dstport}" != "0" ]; then
		CGI_dstip="${CGI_dstip}:${CGI_dstport}"
	fi
	cmdargs="${cmdargs} dst=${CGI_dstip}"
	if [ "${CGI_dscp}" != "" -a "${CGI_dscp}" != "0" ]; then
		cmdargs="${cmdargs} dscp=${CGI_dscp}"
	fi
	[ "${CGI_proto}" != "any" ] && cmdargs="${cmdargs} proto=${CGI_proto}"
	cmdargs="${cmdargs} app=${CGI_appid}"
	if [ "${CGI_action}" = "nat" ]; then
		cmdargs="${cmdargs} action=nat-${CGI_nat_proxy}"
		cmdargs="${cmdargs} nexthop=${CGI_nat_nexthop}"
	else 
		cmdargs="${cmdargs} action=route-${CGI_route_proxy}"
		[ "${CGI_route_nexthop}" = "" ] && CGI_route_nexthop="0.0.0.0"
		cmdargs="${cmdargs} nexthop=${CGI_route_nexthop}"
	fi
	if [ "${CGI_vlan}" != "" -a "${CGI_vlan}" != "0-0" -a "${CGI_vlan}" != "0" ]; then
		cmdargs="${cmdargs} vlan=${CGI_vlan}"
	fi
	[ "${CGI_ttl}" != "" ] && cmdargs="${cmdargs} ttl=${CGI_ttl}"
	if [ "${CGI_desc}" = "" ]; then
		cmdargs="${cmdargs} desc=NULL"
	else
		cmdargs="${cmdargs} desc=${CGI_desc}"
	fi
	cmdargs="${cmdargs} disable=${CGI_disable}"
	[ "${CGI_schtime}" = "" ] && CGI_schtime=0
	cmdargs="${cmdargs} schtime=${CGI_schtime}"
	errmsg=`${FLOWEYE} route set ${cmdargs}`
	if [ "$?" != "0" ]; then
		afm_dialog_msg "出现错误:${errmsg}"
	else
		afm_load_page 0 "/cgi-bin/Route/${returnurl}"
		exit 0
	fi
else
	for nameval in `${FLOWEYE} route get id=${CGI_id}`
	do
		eval "CGI_${nameval}"
	done
	CGI_polno="${CGI_id}"
	CGI_srcip="${CGI_src}"
	[ "${CGI_srcport}" = "any" ] && CGI_srcport=""
	CGI_dstip="${CGI_dst}"
	[ "${CGI_dstport}" = "any" ] && CGI_dstport=""
	if [ "${CGI_action}" = "nat" ]; then
		CGI_nat_proxy="${CGI_actpxyname}"
		CGI_nat_nexthop="${CGI_nexthop}"
		CGI_route_proxy="_NULL_"
		CGI_route_nexthop="0.0.0.0"
	else
		CGI_nat_proxy="_NULL_"
		CGI_nat_nexthop="_NULL_"
		CGI_route_proxy="${CGI_actpxyname}"
		CGI_route_nexthop="${CGI_nexthop}"
	fi
	[ "${CGI_vlan}" = "0-0" -o "${CGI_vlan}" = "0" ] && CGI_vlan=""
	[ "${CGI_schtime}" = "" ] && CGI_schtime=0
	[ "${CGI_ttl}" = "0-255" ] && CGI_ttl=""
	[ "${CGI_desc}" = "NULL" ] && CGI_desc=""
fi

echo -n "
<body onload=\"onLoad()\">
<script type=\"text/javascript\" src=\"/img/wz_tooltip.js\"></script>
<span id=\"hlpno\" style=\"display:none\">编号范围为1~65535,序号小的规则优先匹配</span>
<span id=\"hlpdir\" style=\"display:none\">\"下行\"表示从外网到内网,\"上行\"表示从内网到外网</span>
<span id=\"hlprate\" style=\"display:none\">单IP限速只对内网IP有效,0表示不限速</span>
<span id=\"hlpnext\" style=\"display:none\">(1)\"继续匹配\"表示这一条规则匹配后继续匹配后面的策略<br>(2)\"停止匹配\"表示不再匹配后面的策略<br>(3)当动作为\"阻断\"时此选项无效</span>
<span id=\"hlptos\" style=\"display:none\">当做DSCP标记时，策略只对连接的第一个包进行匹配，该连接后续的包的DSCP值和第一个包保持一致</span>
<span id=\"hlppri\" style=\"display:none\">数字越小，优先级越高;0表示不排队直接通过</span>
<span id=\"hlpnatip\" style=\"display:none\">通过此IP共享上网的最小用户数，0表示忽略,最大为255</span>
"; 
cgi_show_title "策略->策略路由->编辑策略"
tblexists=`${FLOWEYE} table list`

echo -n "
<br>
<form method=post onsubmit=\"return beforeAddRule(this)\" action=\"${myself}\">
<table width=650 border=0 cellspacing=0 cellpadding=3 bgcolor=\"#ffffff\">
<tr id=row1>
	<td width=80></td>
        <td width=120 align=left>策略标识</td>
	<td width=* align=left>
		<input align=right type=text name=polno style=\"width:160\" value=\"${CGI_polno}\" />
		<a style=\"color:#0000ff\" onmouseover=\"TagToTip('hlpno')\" onmouseout=\"UnTip()\">(1~65535)</a>
	</td>
</tr>
"; if [ "${CGI_from}" != "" ]; then 
echo -n "
<tr id=row1>
        <td></td>
        <td align=left>有效时间</td>
        <td align=left>
                <select name=schtime style=\"width:160\" value=\"${CGI_schtime}\">
                ";
                        if [ "${CGI_schtime}" = "0" ]; then
                                echo "<option value=0 selected>所有时间</option>"
                        else
                                echo "<option value=0>所有时间</option>"
                        fi
                        ${FLOWEYE} rtptime list | while read id name theothers
                        do
                                if [ "${CGI_schtime}" = "${id}" ]; then
                                        echo "<option value=${id} selected>${name}</option>"
                                else
                                        echo "<option value=${id}>${name}</option>"
                                fi
                        done
                
echo -n "
                </select>
        </td>
</tr>
"; fi 
echo -n "
<tr id=row1>
	<td></td>
        <td align=left>备注信息</td>
	<td align=left>
		<input align=right type=text name=desc style=\"width:240\" value=\"${CGI_desc}\" />
		&nbsp;(不超过30个汉字或60个英文字符)
	</td>
</tr>
</table>
<br>
<table style=\"width:650; border-bottom:1px #787882 solid; color:#000000\">
<tr><td align=left style=\"font-size:11px\"><b>匹配条件</b></td></tr>
</table>
<br>
<table width=650 border=0 cellspacing=0 cellpadding=3 bgcolor=\"#ffffff\">
<tr id=row1>
	<td width=80></td>
        <td width=120 align=left>源接口</td>
	<td width=160 align=left>
		<select name=inifname style=\"width:160\" value=\"${CGI_iniftype}.${CGI_inif}\">
		";
			${FLOWEYE} nat listproxy type=routerif.posvrif | while read type id name theothers
			do
				if [ "${CGI_iniftype}" = "proxy" -a "${CGI_inif}" = "${name}" ]; then
					echo "<option value=\"proxy.${name}\" selected>${name}</option>"
				else
					echo "<option value=\"proxy.${name}\">${name}</option>"
				fi
			done
			${FLOWEYE} if list | while read ifname ifmode ifzone theothers
                        do
				[ "${ifzone}" != "inside" ] && continue
                                if [ "${CGI_inif}" = "${ifname}"  -a "${CGI_iniftype}" = "if" ]; then
                                        echo "<option value=\"if.${ifname}\" selected>${ifname}</option>"
                                else
                                        echo "<option value=\"if.${ifname}\">${ifname}</option>"
                                fi
                        done
			if [ "${CGI_iniftype}" = "posvr" -a "${CGI_inif}" = "all" ]; then
				echo "<option value=allposvr selected>PPPOE服务</option>"
			else
				echo "<option value=allposvr>PPPOE服务</option>"
			fi
			if [ "${CGI_inif}" = "any" ]; then
				echo "<option value=any selected>任意接口</option>"
			else
				echo "<option value=any>任意接口</option>"
			fi
		
echo -n "
		</select>
	</td>
	<td width=* align=left></td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>VLAN</td>
        <td align=left><input type=text name=vlan value=\"${CGI_vlan}\" style=\"width:160\"></input></td>
	<td width=* align=left><a style=\"color:#0000ff\">(10或10-20,0或0-0或不填表示任意VLAN)</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>TTL</td>
        <td align=left><input type=text name=ttl value=\"${CGI_ttl}\" style=\"width:160\"></input></td>
	<td width=* align=left><a style=\"color:#0000ff\">(10或10-20,不填表示任意TTL)</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>源地址</td>
        <td align=left>
		<select name=srctype style=\"width:160\" value=\"${CGI_srctype}\" onchange=\"onSrctypeChanged(this)\">
		"; cgi_show_iptype "${CGI_srctype}" 
echo -n "
		</select>
	</td>
	<td width=* align=left>
        ";
                rngdisplay="none"
                netdisplay="none"
                tbldisplay="none"
                case "${CGI_srctype}" in
                "net")
                        netdisplay="block"
                        ;;
                "iprange")
                        rngdisplay="block"
                        ;;
                "table")
                        tbldisplay="block"
                        ;;
                esac
                srcipval="${CGI_srcip}"
                [ "${CGI_srcip}" = "any" ] && srcipval=""
                echo "<input type=text name=srcipnet value=\"${srcipval}\" style=\"width:180px;display:${netdisplay}\"></input>"
                echo "<input type=text name=srciprng value=\"${srcipval}\" style=\"width:180px;display:${rngdisplay}\"></input>"
                echo "<select name=srciptbl value=\"${srcipval}\" style=\"width:180px;display:${tbldisplay}\">"
                ${FLOWEYE} table list | while read tblid tblname
                do
                        if [ "${CGI_srcip}" = "${tblid}" -o "${CGI_srcip}" = "${tblname}" ]; then
                                echo "<option value=\"${tblid}\" selected>${tblname}</option>"
                        else
                                echo "<option value=\"${tblid}\">${tblname}</option>"
                        fi
                done
                echo "</select>"
        
echo -n "
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>源端口</td>
        <td><input type=text name=srcport value=\"${CGI_srcport}\" style=\"width:160\"></input></td>
	<td width=* align=left><a style=\"color:#0000ff\">(80或8000-8100，0表示任意端口)</a></td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>目标地址</td>
        <td align=left>
		<select name=dsttype style=\"width:160\" value=\"${CGI_dsttype}\" onchange=\"onDsttypeChanged(this)\">
		"; cgi_show_iptype "${CGI_dsttype}" 
echo -n "
		</select>
	</td>
	<td width=* align=left>
        ";
                rngdisplay="none"
                netdisplay="none"
                tbldisplay="none"
                case "${CGI_dsttype}" in
                "net")
                        netdisplay="block"
                        ;;
                "iprange")
                        rngdisplay="block"
                        ;;
                "table")
                        tbldisplay="block"
                        ;;
                esac
                dstipval="${CGI_dstip}"
                [ "${CGI_dstip}" = "any" ] && dstipval=""
                echo "<input type=text name=dstipnet value=\"${dstipval}\" style=\"width:180px;display:${netdisplay}\"></input>"
                echo "<input type=text name=dstiprng value=\"${dstipval}\" style=\"width:180px;display:${rngdisplay}\"></input>"
                echo "<select name=dstiptbl value=\"${dstipval}\" style=\"width:180px;display:${tbldisplay}\">"
                ${FLOWEYE} table list | while read tblid tblname
                do
                        if [ "${CGI_dstip}" = "${tblid}" -o "${CGI_dstip}" = "${tblname}" ]; then
                                echo "<option value=\"${tblid}\" selected>${tblname}</option>"
                        else
                                echo "<option value=\"${tblid}\">${tblname}</option>"
                        fi
                done
                echo "</select>"
        
echo -n "
	</td>
</tr>
<tr id=row1>
	<td></td>
        <td align=left>目标端口</td>
        <td align=left><input type=text name=dstport value=\"${CGI_dstport}\" style=\"width:160\"></input></td>
	<td width=* align=left><a style=\"color:#0000ff\">(80或8000-8100，0表示任意端口)</a></td>
</tr>
";
[ "${CGI_appid}" = "" ] && CGI_appid="any"
appname=`${FLOWEYE} app name ${CGI_appid}`

echo -n "
<tr id=row1>
	<td></td>
        <td align=left>传输协议</td>
        <td><select name=proto value=\"${CGI_proto}\" style=\"width:160\">
		";
			case "${CGI_proto}" in
			"tcp"|"TCP")
				echo "<option value=any>任意</option>"
				echo "<option value=TCP selected>TCP</option>"
				echo "<option value=UDP>UDP</option>"
				echo "<option value=ICMP>ICMP</option>"
				;;
			"udp"|"UDP")
				echo "<option value=any>任意</option>"
				echo "<option value=TCP>TCP</option>"
				echo "<option value=UDP selected>UDP</option>"
				echo "<option value=ICMP>ICMP</option>"
				;;
			"icmp"|"ICMP")
				echo "<option value=any>任意</option>"
				echo "<option value=TCP>TCP</option>"
				echo "<option value=UDP>UDP</option>"
				echo "<option value=ICMP selected>ICMP</option>"
				;;
			*)
				echo "<option value=any selected>任意</option>"
				echo "<option value=TCP>TCP</option>"
				echo "<option value=UDP>UDP</option>"
				echo "<option value=ICMP>ICMP</option>"
				;;
			esac
		
echo -n "
		</select>
	</td>
        <td width=* align=left></td>
</tr>
"; if [ ${JOS_RELEASE} -ne 0 ]; then 
echo -n "
<tr id=row1>
	<td></td>
        <td align=left>应用协议</td>
        <td align=left>
		<input type=hidden name=appid value=\"${CGI_appid}\"></input>
		<input type=text name=appname value=\"${appname}\" disabled style=\"width:160\">
	</td>
	<td width=* class=cssTDArial align=left>
	  <input type=button name=tmp value=\"选择应用...\" style=\"width:80px\" onclick=\"selectApp('${CGI_appid}')\"></input>
	</td>
</tr>
"; else 
echo -n "
<tr id=row1>
	<td></td>
        <td align=left>应用协议</td>
        <td align=left>
		<input type=hidden name=appid value=\"any\"></input>
		<input type=text name=appname value=\"任意协议\" disabled style=\"width:160\">
	</td>
	<td width=* class=cssTDArial style=\"color:#ff0000\" align=left>这是标准版，不支持应用路由</td>
</tr>
"; fi 
echo -n "
<tr id=row1>
	<td></td>
        <td align=left>DSCP</td>
        <td align=left><input type=text name=dscp value=\"${CGI_dscp}\" style=\"width:160\"></input></td>
	<td width=* align=left></td>
</tr>
</table>
<br>
<table style=\"width:650; border-bottom:1px #787882 solid; color:#000000\">
<tr><td align=left style=\"font-size:11px\"><b>执行动作</b></td></tr>
</table>
<br>
<table width=650 border=0 cellspacing=0 cellpadding=3 bgcolor=\"#ffffff\">
<tr id=row1>
	<td width=80></td>
        <td width=120 align=left>执行动作</td>
        <td width=160>
		<select name=action value=\"${CGI_action}\" style=\"width:100%\" onchange=\"onActionChanged(this)\">
		";
			if [ "${CGI_action}" = "nat" ]; then
				echo "<option value=\"nat\" selected>NAT</option>"
				echo "<option value=\"route\">路由</option>"
			else
				echo "<option value=\"nat\">NAT</option>"
				echo "<option value=\"route\" selected>路由</option>"
			fi
		
echo -n "
		</select>
	</td>
        <td width=* align=left></td>
</tr>
</table>
<table id=idNAT style=\"font:14px;width:650px\" border=0 cellspacing=0 cellpadding=3 bgcolor=\"#ffffff\">
<tr id=row1>
	<td width=80></td>
        <td width=120 align=left>NAT线路</td>
        <td width=160>
		<select name=nat_proxy value=\"${CGI_nat_proxy}\" style=\"width:100%\">
		";
			${FLOWEYE} wangroup list | while read id name pxycnt theothers
			do
				[ ${pxycnt} -eq 0 ] && continue
				if [ "${CGI_actpxyname}" = "_wg.${name}" ]; then
					echo "<option value=\"_wg.${name}\" selected>${name}</option>"
				else
					echo "<option value=\"_wg.${name}\">${name}</option>"
				fi
			done
			${FLOWEYE} nat listproxy type=proxy.pppoe | while read type id name theothers
			do
				if [ "${CGI_actpxyname}" = "${name}" ]; then
					echo "<option value=\"${name}\" selected>${name}</option>"
				else
					echo "<option value=\"${name}\">${name}</option>"
				fi
			done
			if [ "${CGI_actpxyname}" = "_NULL_" ]; then
				echo "<option value=\"_NULL_\" selected>空线路</option>"
			else
				echo "<option value=\"_NULL_\">空线路</option>"
			fi
		
echo -n "
		</select>
	</td>
        <td width=* align=left></td>
</tr>
<tr id=row1>
	<td width=80></td>
        <td width=120 align=left>下一跳</td>
        <td width=160>
		<select name=nat_nexthop value=\"${CGI_nat_nexthop}\" style=\"width:100%\">
		";
			if [ "${CGI_nat_nexthop}" = "_NULL_" ]; then
				echo "<option value=\"_NULL_\" selected>空线路</option>"
			else
				echo "<option value=\"_NULL_\">空线路</option>"
			fi
			${FLOWEYE} nat listproxy type=proxy | while read type id name theothers
			do
				if [ "${CGI_nat_nexthop}" = "${name}" ]; then
					echo "<option value=\"${name}\" selected>${name}</option>"
				else
					echo "<option value=\"${name}\">${name}</option>"
				fi
			done
		
echo -n "
		</select>
	</td>
        <td width=* align=left><a style=\"color:#0000ff\">(如果选择空线路，则走上面选择的NAT线路)</a></td>
</tr>
</table>
<table id=idROUTE style=\"font:14px;width:650px\" border=0 cellspacing=0 cellpadding=3 bgcolor=\"#ffffff\">
<tr id=row1>
	<td width=80></td>
        <td width=120 align=left>路由线路</td>
        <td width=160>
		<select name=route_proxy value=\"${CGI_route_proxy}\" style=\"width:100%\">
		";
			${FLOWEYE} nat listproxy | while read type id name theothers
			do
				if [ "${CGI_route_proxy}" = "${name}" ]; then
					echo "<option value=\"${name}\" selected>${name}</option>"
				else
					echo "<option value=\"${name}\">${name}</option>"
				fi
			done
		
echo -n "
		</select>
	</td>
        <td width=* align=left></td>
</tr>
<tr id=row1>
	<td width=80></td>
        <td width=120 align=left>下一跳</td>
        <td width=160>
		<input type=text name=route_nexthop value=\"${CGI_route_nexthop}\" style=\"width:100%\"></input>
	</td>
        <td width=* align=left><a style=\"color:#0000ff\">(如为空或0.0.0.0，则使用目标地址或线路的网关)</a></td>
</tr>
</table>
<table style=\"width:650; border-bottom:1px #787882 solid; color:#0000ff\">
<tr><td align=right>&nbsp;</td></tr>
</table>
<table style=\"width:650\"> 
<tr>
        <td align=right>
		<input type=submit id=newbtn style=\"width:80\" value=\"提交\"></input>
		<input type=button id=newbtn style=\"width:80\" value=\"取消\" onclick=\"onCancel()\"></input>
		<input type=hidden name=disable value=\"${CGI_disable}\" />
		<input type=hidden name=from value=\"${CGI_from}\" />
	</td>
</tr>
</table>
</form>
</body>
</html>
";