#!/bin/sh
#This script is created by ssparser automatically. The parser first created by MaoShouyan
printf "Content-type: text/html;charset=gb2312
Cache-Control: no-cache

"
echo -n "";
. ../common/common.sh
myself="/cgi-bin/Route/`basename $0`"
MOD_TAB_LIST="LAN接口#/cgi-bin/Route/iflan_list WAN线路#/cgi-bin/Route/proxy_list"

echo -n "
<script type=\"text/javascript\" src=\"/img/common.js\"></script>
<script language=\"javascript\">
function onAddProxy()
{
	window.location.href = \"/cgi-bin/Route/proxy_add\";
}
function onImportProxy()
{
	window.location.href = \"/cgi-bin/Route/proxy_import\";
}
function onExportProxy()
{
	window.location.href = \"/cgi-bin/Route/proxy_export\";
}
function onDeleteProxy(id)
{
	if (confirm(\"系统将删除所有使用此线路的规则，确定要删除此线路吗?\")) 
		window.location.href = \"${myself}?action=delete&pxyid=\" + id; 
}
function showProxy(type, proxyname)
{
        var url;
	url = \"/cgi-bin/Monitor/proxy_show?proxyname=\" + proxyname;
	ShowWindow(url, \"\", 620, 700);
}
function editProxy(type, name)
{
	window.location.href = \"/cgi-bin/Route/proxy_edit?proxyname=\" + name;
}
function enableProxy(pxyid)
{
	window.location.href = \"${myself}?action=enable&id=\" + pxyid;
}
function disableProxy(pxyid)
{
	if (confirm(\"确定要禁用该线路?\"))
		window.location.href = \"${myself}?action=disable&id=\" + pxyid;
}
function onAddIflan()
{
        window.location.href = \"/cgi-bin/Route/iflan_add\";
}
function onDeleteIflan(id)
{
        if (confirm(\"系统将删除和此虚拟接口相关的所有路由策略，确定要删除?\"))
                window.location.href = \"${myself}?action=delete&pxyid=\" + id;
}
function pppoeRedial(name)
{
	if (confirm(\"确定要重拨吗?\"))
		window.location.href = \"${myself}?action=redial&proxyname=\" + name;
}
function onEditWG(id, name, type)
{
	window.location.href = \"/cgi-bin/Route/wg_edit?id=\" + id + 
		\"&name=\" + name + \"&type=\" + type;
}
function onAddWGwan(id, name)
{
	window.location.href = \"/cgi-bin/Route/wg_addwan?id=\" + id + \"&name=\" + name;
}
function onEditWGwan(id, name, proxy, weight)
{
	window.location.href = \"/cgi-bin/Route/wg_editwan?id=\" + id + 
		\"&name=\" + name + \"&proxy=\" + proxy + \"&weight=\" + weight;
}
function onRmvWGwan(id, proxy)
{
	if (confirm(\"确定要从WAN群组中删除线路?\"))
		window.location.href = \"${myself}?action=rmvwgwan&id=\" + id + \"&proxy=\" + proxy;
}
function showIf(ifname)
{
        var url = \"/cgi-bin/Monitor/if_show?name=\" + ifname; 
        ShowWindow(url, \"\", 720, 700);
}
function onRtgraph(name, type)
{
        var url = \"/cgi-bin/Monitor/ifpxy_rtgraph?name=\" + name + \"&type=\" + type;
        ShowWindow(url, \"\", 720, 680);
}
function onSelectItemSub(obj)
{
	var i = 0, count = 0;
	var wans = document.getElementsByName(\"wan\");
	for (i = 0; i < wans.length; i++) {
		if (wans[i].checked) count++;
	}
	if (count > 0) {
		document.getElementsByName(\"a_redial\")[0].style.color = \"#0000ff\";
		document.getElementsByName(\"a_delete\")[0].style.color = \"#0000ff\";
		document.getElementsByName(\"a_enable\")[0].style.color = \"#0000ff\";
		document.getElementsByName(\"a_disable\")[0].style.color = \"#0000ff\";
		if (count == wans.length)
			document.getElementsByName(\"cb_main\")[0].checked = true;
		else
			document.getElementsByName(\"cb_main\")[0].checked = false;
	}
	else {
		document.getElementsByName(\"a_redial\")[0].style.color = \"#c0c0c0\";
		document.getElementsByName(\"a_delete\")[0].style.color = \"#c0c0c0\";
		document.getElementsByName(\"a_enable\")[0].style.color = \"#c0c0c0\";
		document.getElementsByName(\"a_disable\")[0].style.color = \"#c0c0c0\";
	}
}
function onSelectItemMain(obj)
{
	var i;
	var wans = document.getElementsByName(\"wan\");
	if (wans.length <= 0) {
		document.getElementsByName(\"a_redial\")[0].style.color = \"#c0c0c0\";
		document.getElementsByName(\"a_delete\")[0].style.color = \"#c0c0c0\";
		document.getElementsByName(\"a_enable\")[0].style.color = \"#c0c0c0\";
		document.getElementsByName(\"a_disable\")[0].style.color = \"#c0c0c0\";
		return;
	}
	
	if (obj.checked) {
		document.getElementsByName(\"a_redial\")[0].style.color = \"#0000ff\";
		document.getElementsByName(\"a_delete\")[0].style.color = \"#0000ff\";
		document.getElementsByName(\"a_enable\")[0].style.color = \"#0000ff\";
		document.getElementsByName(\"a_disable\")[0].style.color = \"#0000ff\";
	}
	else {
		document.getElementsByName(\"a_redial\")[0].style.color = \"#c0c0c0\";
		document.getElementsByName(\"a_delete\")[0].style.color = \"#c0c0c0\";
		document.getElementsByName(\"a_enable\")[0].style.color = \"#c0c0c0\";
		document.getElementsByName(\"a_disable\")[0].style.color = \"#c0c0c0\";
	}
	for (i = 0; i < wans.length; i++)
		wans[i].checked = obj.checked;
}
function onDeleteSelectItem(obj)
{
	var i = 0, items =\"\";
	var wans = document.getElementsByName(\"wan\");
	for (i = 0; i < wans.length; i++) {
		if (wans[i].checked)
			items += wans[i].value + \",\";
	}
	
	if(items!=\"\") {
		if (confirm(\"系统将删除选中线路的虚拟接口和相关的所有路由策略，确定要删除?\")) {
			items = items.substr(0, items.length - 1);
			window.location.href = \"${myself}?action=batchdelete&items=\"+items;
		}
	}
}
function onRedialSelectItem(obj)
{
	var i = 0, items =\"\";
	var wans = document.getElementsByName(\"wan\");
	for (i = 0; i < wans.length; i++) {
		if (wans[i].checked)
			items += wans[i].value + \",\";
	}
	if(items != \"\") {
		if (confirm(\"确定要对所选线路进行重拨?\")) {
			items = items.substr(0, items.length - 1);
			window.location.href = \"${myself}?action=batchredial&items=\"+items;
		}
	}
}
function onEnableSelectItem(obj)
{
	var i = 0, items =\"\";
	var wans = document.getElementsByName(\"wan\");
	for (i = 0; i < wans.length; i++) {
		if (wans[i].checked)
			items += wans[i].value + \",\";
	}
	if(items != \"\") {
		if (confirm(\"确定要启用所选线路?\")) {
			items = items.substr(0, items.length - 1);
			window.location.href = \"${myself}?action=batchenable&items=\"+items;
		}
	}
}
function onDisableSelectItem(obj)
{
	var i = 0, items =\"\";
	var wans = document.getElementsByName(\"wan\");
	for (i = 0; i < wans.length; i++) {
		if (wans[i].checked)
			items += wans[i].value + \",\";
	}
	if(items != \"\") {
		if (confirm(\"确定要禁用所选线路?\")) {
			items = items.substr(0, items.length - 1);
			window.location.href = \"${myself}?action=batchdisable&items=\"+items;
		}
	}
}
function getremarks()
{
	var i, remarkobj;
	var wannames = document.getElementsByName(\"wanname\");
	if (wannames.length <= 0)
		return;
	AJXS({type: 'POST', 
	       url: '/cgi-bin/Route/ajax_proxy_remark', 
	     error: function(status){setTimeout(getremarks, 4000);},
	   success: function(data) { 
		var d;
		try {
			d = eval('('+data+')');
		} catch(e) {
			setTimeout(getremarks, 4000);
			return;
		}
		for (i = 0; i < d.length; i++) {
			remarkobj = document.getElementById(\"remark_\" + d[i].name);
			if (remarkobj != null)
				remarkobj.innerHTML = d[i].remark;
		}
	}});
}
function getproxystats()
{
	var row;
	AJXS({type: 'POST', 
	       url: '/cgi-bin/Route/ajax_proxy_list', 
	     error: function(status){setTimeout(getproxystats, 4000);},
	   success: function(data) { 
		var d, i;
		var stateobj;
		var inbpsobj, outbpsobj, flowcntobj;
		try {
			d = eval('('+data+')');
		} catch(e) {
			setTimeout(getproxystats, 4000);
			return;
		}
		for (i = 0; i < d.length; i++) {
			stateobj = document.getElementById(\"state_\" + d[i].id);
			if (stateobj != null) {
				if (d[i].standby == \"yes\") {
					stateobj.innerHTML = \"<a style=color:#00ff00>待机</a>\";
					document.getElementsByName(\"pxy_\" + d[i].id)[0].id = \"row4\";
					document.getElementById(\"pxycolor_\" + d[i].id).style.color = \"#00ff00\";
				}
				else
				if (d[i].disable == \"yes\") {
					stateobj.innerText = \"禁用\";
					document.getElementsByName(\"pxy_\" + d[i].id)[0].id = \"row4\";
					document.getElementById(\"pxycolor_\" + d[i].id).style.color = \"#c0c0c0\";
				}
				else {
					document.getElementsByName(\"pxy_\" + d[i].id)[0].id = \"row1\";
					document.getElementById(\"pxycolor_\" + d[i].id).style.color = \"#0000ff\";
					if (d[i].state == \"1\")
						stateobj.innerHTML = \"<img src='/img/yes.png' style='margin-right:5px;vertical-align:middle' />\";
					else
						stateobj.innerHTML = \"<img src='/img/no.png' style='margin-right:5px;vertical-align:middle' />\";
				}
			}
			inbpsobj = document.getElementById(\"inbps_\" + d[i].id);
			if (inbpsobj != null) inbpsobj.innerHTML = d[i].inbps;
			outbpsobj = document.getElementById(\"outbps_\" + d[i].id);
			if (outbpsobj != null) outbpsobj.innerHTML = d[i].outbps;
			flowcntobj = document.getElementById(\"flowcnt_\" + d[i].id);
			if (flowcntobj != null) flowcntobj.innerHTML = d[i].flowcnt;
			outbpsobj = document.getElementById(\"dnsstat_\" + d[i].id);
			if (outbpsobj != null) outbpsobj.innerHTML = d[i].dnsreq + \" / \"  + d[i].dnsfail + \"%\";
		}
		
		setTimeout(getproxystats, 4000);
	}});
}
function onresize()
{
        if (document.body.clientWidth > 1280)
                document.getElementById(\"mytbl\").style.width=\"100%\";
        else
                document.getElementById(\"mytbl\").style.width=\"1280\";
}
function onloaddoc()
{
	getremarks();
	getproxystats();
	onresize();
}
</script>
";
if [ "${CGI_action}" = "delete" ]; then
	operator_check "${myself}"
	errmsg=`${FLOWEYE} nat rmvproxy ${CGI_pxyid}`
	if [ "$?" != "0" ]; then
		afm_dialog_msg "操作失败:${errmsg}"
	fi
elif [ "${CGI_action}" = "redial" ]; then
	operator_check "${myself}"
	errmsg=`${FLOWEYE} nat setpppoe name=${CGI_proxyname} redial=1`
	if [ "$?" != "0" ]; then
		afm_dialog_msg "操作失败:${errmsg}"
	else
		sleep 1
	fi
elif [ "${CGI_action}" = "batchdelete" ]; then
	operator_check "${myself}"
	errcount=0
	allcount=0
	CGI_items=`echo ${CGI_items} | tr ',' ' '`
	for id in ${CGI_items}
	do
		errmsg=`${FLOWEYE} nat rmvproxy ${id}`
		[ "$?" != "0" ] && errcount=$((${errcount}+1))
		allcount=$((${allcount}+1))
	done
	[ "${errcount}" != "0" ] && afm_dialog_msg "总共${allcount}个，操作失败${errcount}个: 可能线路正在使用中，无法删除。"
elif [ "${CGI_action}" = "batchredial" ]; then
	operator_check "${myself}"
	errcount=0
	allcount=0
	CGI_items=`echo ${CGI_items} | tr ',' ' '`
	for name in ${CGI_items}
	do
		errmsg=`${FLOWEYE} nat setpppoe name=${name} redial=1`
		[ "$?" != "0" ] && errcount=$((${errcount}+1))
		allcount=$((${allcount}+1))
		echo "<br><b><p style=\"color:#0000ff;font-size:13px\">发送重拨指令给线路\"${name}\"......</p>"
		sleep .1
	done
	sleep .5
	afm_load_page 0 "${myself}"
	exit 0
elif [ "${CGI_action}" = "enable" ]; then
	operator_check "${myself}"
	errmsg=`${FLOWEYE} nat config enableproxy=${CGI_id}`
	if [ "$?" != "0" ]; then
		afm_dialog_msg "操作失败:${errmsg}"
	fi
elif [ "${CGI_action}" = "disable" ]; then
	operator_check "${myself}"
	errmsg=`${FLOWEYE} nat config disableproxy=${CGI_id}`
	if [ "$?" != "0" ]; then
		afm_dialog_msg "操作失败:${errmsg}"
	fi
elif [ "${CGI_action}" = "batchenable" ]; then
	operator_check "${myself}"
	CGI_items=`echo ${CGI_items} | tr ',' ' '`
	cmdargs=""
	for name in ${CGI_items}
	do
		cmdargs="${cmdargs} enableproxy=${name}"
	done
	errmsg=`${FLOWEYE} nat config ${cmdargs}`
	afm_load_page 0 "${myself}"
	exit 0
elif [ "${CGI_action}" = "batchdisable" ]; then
	operator_check "${myself}"
	CGI_items=`echo ${CGI_items} | tr ',' ' '`
	cmdargs=""
	for name in ${CGI_items}
	do
		cmdargs="${cmdargs} disableproxy=${name}"
	done
	errmsg=`${FLOWEYE} nat config ${cmdargs}`
	afm_load_page 0 "${myself}"
	exit 0
fi

echo -n "
<body onload=\"onloaddoc();\">
"; 
if [ "${CGI_browsertitle}" = "" ]; then
	cgi_show_title "应用路由->对象->接口线路" 
fi
cgi_print_mod_header "WAN线路" "100%"

echo -n "
<table id=mytbl width=\"100%\" border=0 cellspacing=1 cellpadding=1> 
<tr id=tblhdr>
	<td width=20  align=center><input name=cb_main type=checkbox style=\"color:#0000ff\" value='${id}' onclick=\"onSelectItemMain(this)\"/></td>
	<td width=35  align=right>序号</td>
	<td width=110 align=right>线路名称</td>
	<td width=65  align=right>网卡</td>
	<td width=65  align=right>状态</td>
	<td width=110 align=right>IP地址</td>
	<td width=110 align=right>网关地址</td>
	<td width=50  align=right>VLAN</td>
	<td width=120 align=right>DNS牵引/失败率</td>
	<td width=80  align=right>流入速率</td>
	<td width=80  align=right>流出速率</td>
	<td width=80  align=right>连接数</td>
	<td width=*   align=right>备注</td>
	<td width=200 align=right>
		<a name=\"a_enable\" style=\"color:#c0c0c0;font-size:13px\" href=\"javascript:void(0)\" onclick=\"onEnableSelectItem(this)\">启用&nbsp;</a>
		<a name=\"a_disable\" style=\"color:#c0c0c0;font-size:13px\" href=\"javascript:void(0)\" onclick=\"onDisableSelectItem(this)\">禁用&nbsp;</a>
		<a name=\"a_redial\" style=\"color:#c0c0c0;font-size:13px\" href=\"javascript:void(0)\" onclick=\"onRedialSelectItem(this)\">重拨&nbsp;</a>
		<a name=\"a_delete\" style=\"color:#c0c0c0;font-size:13px\" href=\"javascript:void(0)\" onclick=\"onDeleteSelectItem(this)\">删除&nbsp;</a>
		<a style=\"color:#0000ff;font-size:13px\" href=\"javascript:onAddProxy()\">添加>>&nbsp;</a>
	</td>
</tr>
";
idname="row1"
natcount=0
${FLOWEYE} nat listproxy type=proxy.pppoe | while read type id name ifname addr gateway dnsaddr vlan \
gatewaymac flowcnt ttl inbytes outbytes inbps outbps dnsreqs dnsfailrate linkup disabled theothers
do
	natcount=$((${natcount}+1))
	if [ "${disabled}" = "disable" ]; then
    		echo "<tr id=row4 name=pxy_${id}>"
	else
    		echo "<tr id=${idname} name=pxy_${id}>"
	fi

echo -n "
    <td align=center>
	<input type=hidden name=wanname value=\"${name}\" />
	<input type=checkbox name=wan style=\"color:#0000ff\" value='${id}' onclick=\"onSelectItemSub(this)\">
    </td>
    <td align=right>${natcount}</td>
    <td align=right><a id=pxycolor_${id} style=\"color:#0000ff\" href=\"javascript:showProxy('${type}', '${name}')\">${name}</a></td>
    <td align=right><a style=\"color:#0000ff\" href=\"javascript:showIf('${ifname}')\">${ifname}</a></td>
    <td align=right id=state_${id}></td>
    <td align=right>${addr}</td>
    <td align=right>${gateway}</td>
"; [ "${vlan}" = "0" ] && vlan="&nbsp;" 
echo -n "
    <td align=right>${vlan}</td>
    <td align=right><span id=\"dnsstat_${id}\">${dnsreqs}/${dnsfailrate}%</span></td>
    <td align=right><span id=\"inbps_${id}\">${inbps}</span></td>
    <td align=right><span id=\"outbps_${id}\">${outbps}</span></td>
    <td align=right><span id=\"flowcnt_${id}\">${flowcnt}</span></td>
    <td align=right><span id=\"remark_${name}\"></span></td>
    <td align=right>
"; if [ "${type}" = "pppoe" ]; then 
echo -n "
	<a style=\"color:#0000ff\" href=\"javascript:pppoeRedial('${name}')\">重拨</a>&nbsp;&nbsp;
"; fi 
echo -n "
	<img src=\"/img/delete.png\" style=\"margin-top:3px\" onclick=\"onDeleteProxy('${id}')\"  title=\"删除线路\" />&nbsp;
	"; if [ "${disabled}" != "disable" ]; then 
echo -n "
                <img src=\"/img/disable.png\" style=\"margin-top: 3px\" onclick=\"disableProxy('${id}')\" title=\"禁用线路\" />&nbsp;
	"; else 
echo -n "
                <img src=\"/img/enable.png\" style=\"margin-top: 3px\" onclick=\"enableProxy('${id}')\" title=\"启用线路\" />&nbsp;
	"; fi 
echo -n "
    </td>
</tr>
"; 	if [ "${idname}" = "row1" ]; then
		idname="row2"
	else
		idname="row1"
	fi
done

echo -n "
</table>
</body>
</html>
";